; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -mattr=+morello -S -passes=loop-vectorize,dce,instcombine %s -o - | FileCheck %s
target datalayout = "e-m:e-i64:64-i128:128-n32:64-S128-pf200:128:128:128:64"
target triple = "aarch64-none--elf"

define ptr @test(ptr noalias %dst, ptr noalias nocapture readonly %src, i64 %len) {
; CHECK-LABEL: define ptr @test
; CHECK-SAME: (ptr noalias [[DST:%.*]], ptr noalias nocapture readonly [[SRC:%.*]], i64 [[LEN:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_18:%.*]] = icmp ugt i64 [[LEN]], 63
; CHECK-NEXT:    br i1 [[CMP_18]], label [[PREHEADER:%.*]], label [[THEEND:%.*]]
; CHECK:       preheader:
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[LEN]], -64
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[DST]], i64 [[TMP2]]
; CHECK-NEXT:    br label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[ALIGNED_DST_021:%.*]] = phi ptr [ [[INCDEC_PTR7:%.*]], [[BODY]] ], [ [[DST]], [[PREHEADER]] ]
; CHECK-NEXT:    [[ALIGNED_SRC_020:%.*]] = phi ptr [ [[INCDEC_PTR6:%.*]], [[BODY]] ], [ [[SRC]], [[PREHEADER]] ]
; CHECK-NEXT:    [[LEN_ADDR_019:%.*]] = phi i64 [ [[SUB:%.*]], [[BODY]] ], [ [[LEN]], [[PREHEADER]] ]
; CHECK-NEXT:    [[INCDEC_PTR:%.*]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_SRC_020]], i64 1
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr [[ALIGNED_SRC_020]], align 16
; CHECK-NEXT:    [[INCDEC_PTR1:%.*]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_DST_021]], i64 1
; CHECK-NEXT:    store ptr addrspace(200) [[TMP3]], ptr [[ALIGNED_DST_021]], align 16
; CHECK-NEXT:    [[INCDEC_PTR2:%.*]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_SRC_020]], i64 2
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr [[INCDEC_PTR]], align 16
; CHECK-NEXT:    [[INCDEC_PTR3:%.*]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_DST_021]], i64 2
; CHECK-NEXT:    store ptr addrspace(200) [[TMP4]], ptr [[INCDEC_PTR1]], align 16
; CHECK-NEXT:    [[INCDEC_PTR4:%.*]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_SRC_020]], i64 3
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr addrspace(200), ptr [[INCDEC_PTR2]], align 16
; CHECK-NEXT:    [[INCDEC_PTR5:%.*]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_DST_021]], i64 3
; CHECK-NEXT:    store ptr addrspace(200) [[TMP5]], ptr [[INCDEC_PTR3]], align 16
; CHECK-NEXT:    [[INCDEC_PTR6]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_SRC_020]], i64 4
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr addrspace(200), ptr [[INCDEC_PTR4]], align 16
; CHECK-NEXT:    [[INCDEC_PTR7]] = getelementptr inbounds ptr addrspace(200), ptr [[ALIGNED_DST_021]], i64 4
; CHECK-NEXT:    store ptr addrspace(200) [[TMP6]], ptr [[INCDEC_PTR5]], align 16
; CHECK-NEXT:    [[SUB]] = add i64 [[LEN_ADDR_019]], -64
; CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i64 [[SUB]], 63
; CHECK-NEXT:    br i1 [[CMP]], label [[BODY]], label [[LOOPEXIT:%.*]]
; CHECK:       loopexit:
; CHECK-NEXT:    br label [[THEEND]]
; CHECK:       theEnd:
; CHECK-NEXT:    [[ALIGNED_DST_0_LCSSA:%.*]] = phi ptr [ [[DST]], [[ENTRY:%.*]] ], [ [[SCEVGEP]], [[LOOPEXIT]] ]
; CHECK-NEXT:    ret ptr [[ALIGNED_DST_0_LCSSA]]
;
entry:
  %cmp.18 = icmp ugt i64 %len, 63
  br i1 %cmp.18, label %preheader, label %theEnd

preheader:
  %tmp2 = and i64 %len, -64
  %scevgep = getelementptr i8, ptr %dst, i64 %tmp2
  br label %body

body:
  %aligned_dst.021 = phi ptr [ %incdec.ptr7, %body ], [ %dst, %preheader ]
  %aligned_src.020 = phi ptr [ %incdec.ptr6, %body ], [ %src, %preheader ]
  %len.addr.019 = phi i64 [ %sub, %body ], [ %len, %preheader ]
  %incdec.ptr = getelementptr inbounds ptr addrspace(200), ptr %aligned_src.020, i64 1
  %tmp3 = load ptr addrspace(200), ptr %aligned_src.020, align 16
  %incdec.ptr1 = getelementptr inbounds ptr addrspace(200), ptr %aligned_dst.021, i64 1
  store ptr addrspace(200) %tmp3, ptr %aligned_dst.021, align 16
  %incdec.ptr2 = getelementptr inbounds ptr addrspace(200), ptr %aligned_src.020, i64 2
  %tmp4 = load ptr addrspace(200), ptr %incdec.ptr, align 16
  %incdec.ptr3 = getelementptr inbounds ptr addrspace(200), ptr %aligned_dst.021, i64 2
  store ptr addrspace(200) %tmp4, ptr %incdec.ptr1, align 16
  %incdec.ptr4 = getelementptr inbounds ptr addrspace(200), ptr %aligned_src.020, i64 3
  %tmp5 = load ptr addrspace(200), ptr %incdec.ptr2, align 16
  %incdec.ptr5 = getelementptr inbounds ptr addrspace(200), ptr %aligned_dst.021, i64 3
  store ptr addrspace(200) %tmp5, ptr %incdec.ptr3, align 16
  %incdec.ptr6 = getelementptr inbounds ptr addrspace(200), ptr %aligned_src.020, i64 4
  %tmp6 = load ptr addrspace(200), ptr %incdec.ptr4, align 16
  %incdec.ptr7 = getelementptr inbounds ptr addrspace(200), ptr %aligned_dst.021, i64 4
  store ptr addrspace(200) %tmp6, ptr %incdec.ptr5, align 16
  %sub = add i64 %len.addr.019, -64
  %cmp = icmp ugt i64 %sub, 63
  br i1 %cmp, label %body, label %loopexit

loopexit:
  br label %theEnd

theEnd:
  %aligned_dst.0.lcssa = phi ptr [ %dst, %entry ], [ %scevgep, %loopexit ]
  ret ptr %aligned_dst.0.lcssa
}
