; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/address-get-simplify.ll
; RUN: opt < %s -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 -passes=instsimplify -S | FileCheck %s
; RUN: opt < %s -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -passes=instsimplify -S | FileCheck %s

target datalayout = "E-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-n32:64-S128-A200-P200-G200"

; Derived from various existing ptrtoint tests.

declare i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)*)

define i1 @or_cmps_ptr_eq_zero_with_mask_commute1(i64 addrspace(200)* %p, i64 %y) {
; CHECK-LABEL: define i1 @or_cmps_ptr_eq_zero_with_mask_commute1
; CHECK-SAME: (ptr addrspace(200) [[P:%.*]], i64 [[Y:%.*]]) addrspace(200) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[ISNULL:%.*]] = icmp eq ptr addrspace(200) [[P]], null
; CHECK-NEXT:    [[X:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[P]])
; CHECK-NEXT:    [[SOMEBITS:%.*]] = and i64 [[X]], [[Y]]
; CHECK-NEXT:    [[SOMEBITS_ARE_ZERO:%.*]] = icmp eq i64 [[SOMEBITS]], 0
; CHECK-NEXT:    [[R:%.*]] = or i1 [[SOMEBITS_ARE_ZERO]], [[ISNULL]]
; CHECK-NEXT:    ret i1 [[R]]
;
  %isnull = icmp eq i64 addrspace(200)* %p, null
  %p1 = bitcast i64 addrspace(200)* %p to i8 addrspace(200)*
  %x = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p1)
  %somebits = and i64 %x, %y
  %somebits_are_zero = icmp eq i64 %somebits, 0
  %r = or i1 %somebits_are_zero, %isnull
  ret i1 %r
}

define i1 @or_cmps_ptr_eq_zero_with_mask_commute3(i4 addrspace(200)* %p, i4 %y) {
; CHECK-LABEL: define i1 @or_cmps_ptr_eq_zero_with_mask_commute3
; CHECK-SAME: (ptr addrspace(200) [[P:%.*]], i4 [[Y:%.*]]) addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    [[ISNULL:%.*]] = icmp eq ptr addrspace(200) [[P]], null
; CHECK-NEXT:    [[XADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[P]])
; CHECK-NEXT:    [[X:%.*]] = trunc i64 [[XADDR]] to i4
; CHECK-NEXT:    [[SOMEBITS:%.*]] = and i4 [[Y]], [[X]]
; CHECK-NEXT:    [[SOMEBITS_ARE_ZERO:%.*]] = icmp eq i4 [[SOMEBITS]], 0
; CHECK-NEXT:    [[R:%.*]] = or i1 [[SOMEBITS_ARE_ZERO]], [[ISNULL]]
; CHECK-NEXT:    ret i1 [[R]]
;
  %isnull = icmp eq i4 addrspace(200)* %p, null
  %p1 = bitcast i4 addrspace(200)* %p to i8 addrspace(200)*
  %xaddr = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p1)
  %x = trunc i64 %xaddr to i4
  %somebits = and i4 %y, %x
  %somebits_are_zero = icmp eq i4 %somebits, 0
  %r = or i1 %somebits_are_zero, %isnull
  ret i1 %r
}

define i1 @and_cmps_ptr_eq_zero_with_mask_commute2(i4 addrspace(200)* %p, i4 %y) {
; CHECK-LABEL: define i1 @and_cmps_ptr_eq_zero_with_mask_commute2
; CHECK-SAME: (ptr addrspace(200) [[P:%.*]], i4 [[Y:%.*]]) addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    [[XADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[P]])
; CHECK-NEXT:    [[X:%.*]] = trunc i64 [[XADDR]] to i4
; CHECK-NEXT:    [[SOMEBITS:%.*]] = and i4 [[X]], [[Y]]
; CHECK-NEXT:    [[SOMEBITS_ARE_NOT_ZERO:%.*]] = icmp ne i4 [[SOMEBITS]], 0
; CHECK-NEXT:    ret i1 [[SOMEBITS_ARE_NOT_ZERO]]
;
  %isnotnull = icmp ne i4 addrspace(200)* %p, null
  %p1 = bitcast i4 addrspace(200)* %p to i8 addrspace(200)*
  %xaddr = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p1)
  %x = trunc i64 %xaddr to i4
  %somebits = and i4 %x, %y
  %somebits_are_not_zero = icmp ne i4 %somebits, 0
  %r = and i1 %isnotnull, %somebits_are_not_zero
  ret i1 %r
}

define i1 @and_cmps_ptr_eq_zero_with_mask_commute4(i64 addrspace(200)* %p, i64 %y) {
; CHECK-LABEL: define i1 @and_cmps_ptr_eq_zero_with_mask_commute4
; CHECK-SAME: (ptr addrspace(200) [[P:%.*]], i64 [[Y:%.*]]) addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    [[X:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[P]])
; CHECK-NEXT:    [[SOMEBITS:%.*]] = and i64 [[Y]], [[X]]
; CHECK-NEXT:    [[SOMEBITS_ARE_NOT_ZERO:%.*]] = icmp ne i64 [[SOMEBITS]], 0
; CHECK-NEXT:    ret i1 [[SOMEBITS_ARE_NOT_ZERO]]
;
  %isnotnull = icmp ne i64 addrspace(200)* %p, null
  %p1 = bitcast i64 addrspace(200)* %p to i8 addrspace(200)*
  %x = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p1)
  %somebits = and i64 %y, %x
  %somebits_are_not_zero = icmp ne i64 %somebits, 0
  %r = and i1 %isnotnull, %somebits_are_not_zero
  ret i1 %r
}

define i8 addrspace(200)* @D98611_1(i8 addrspace(200)* %c1, i64 %offset) {
; CHECK-LABEL: define ptr addrspace(200) @D98611_1
; CHECK-SAME: (ptr addrspace(200) [[C1:%.*]], i64 [[OFFSET:%.*]]) addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    [[C2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[C1]], i64 [[OFFSET]]
; CHECK-NEXT:    [[PTRTOINT1:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[C1]])
; CHECK-NEXT:    [[PTRTOINT2:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[C2]])
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 [[PTRTOINT2]], [[PTRTOINT1]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[C1]], i64 [[SUB]]
; CHECK-NEXT:    ret ptr addrspace(200) [[GEP]]
;
  %c2 = getelementptr inbounds i8, i8 addrspace(200)* %c1, i64 %offset
  %ptrtoint1 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %c1)
  %ptrtoint2 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %c2)
  %sub = sub i64 %ptrtoint2, %ptrtoint1
  %gep = getelementptr inbounds i8, i8 addrspace(200)* %c1, i64 %sub
  ret i8 addrspace(200)* %gep
}

%struct.A = type { [7 x i8] }

define %struct.A addrspace(200)* @D98611_2(%struct.A addrspace(200)* %c1, i64 %offset) {
; CHECK-LABEL: define ptr addrspace(200) @D98611_2
; CHECK-SAME: (ptr addrspace(200) [[C1:%.*]], i64 [[OFFSET:%.*]]) addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    [[C2:%.*]] = getelementptr inbounds [[STRUCT_A:%.*]], ptr addrspace(200) [[C1]], i64 [[OFFSET]]
; CHECK-NEXT:    [[PTRTOINT1:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[C1]])
; CHECK-NEXT:    [[PTRTOINT2:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[C2]])
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 [[PTRTOINT2]], [[PTRTOINT1]]
; CHECK-NEXT:    [[SDIV:%.*]] = sdiv exact i64 [[SUB]], 7
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_A]], ptr addrspace(200) [[C1]], i64 [[SDIV]]
; CHECK-NEXT:    ret ptr addrspace(200) [[GEP]]
;
  %c2 = getelementptr inbounds %struct.A, %struct.A addrspace(200)* %c1, i64 %offset
  %p1 = bitcast %struct.A addrspace(200)* %c1 to i8 addrspace(200)*
  %p2 = bitcast %struct.A addrspace(200)* %c2 to i8 addrspace(200)*
  %ptrtoint1 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p1)
  %ptrtoint2 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p2)
  %sub = sub i64 %ptrtoint2, %ptrtoint1
  %sdiv = sdiv exact i64 %sub, 7
  %gep = getelementptr inbounds %struct.A, %struct.A addrspace(200)* %c1, i64 %sdiv
  ret %struct.A addrspace(200)* %gep
}

define i32 addrspace(200)* @D98611_3(i32 addrspace(200)* %c1, i64 %offset) {
; CHECK-LABEL: define ptr addrspace(200) @D98611_3
; CHECK-SAME: (ptr addrspace(200) [[C1:%.*]], i64 [[OFFSET:%.*]]) addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    [[C2:%.*]] = getelementptr inbounds i32, ptr addrspace(200) [[C1]], i64 [[OFFSET]]
; CHECK-NEXT:    [[PTRTOINT1:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[C1]])
; CHECK-NEXT:    [[PTRTOINT2:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[C2]])
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 [[PTRTOINT2]], [[PTRTOINT1]]
; CHECK-NEXT:    [[ASHR:%.*]] = ashr exact i64 [[SUB]], 2
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr addrspace(200) [[C1]], i64 [[ASHR]]
; CHECK-NEXT:    ret ptr addrspace(200) [[GEP]]
;
  %c2 = getelementptr inbounds i32, i32 addrspace(200)* %c1, i64 %offset
  %p1 = bitcast i32 addrspace(200)* %c1 to i8 addrspace(200)*
  %p2 = bitcast i32 addrspace(200)* %c2 to i8 addrspace(200)*
  %ptrtoint1 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p1)
  %ptrtoint2 = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %p2)
  %sub = sub i64 %ptrtoint2, %ptrtoint1
  %ashr = ashr exact i64 %sub, 2
  %gep = getelementptr inbounds i32, i32 addrspace(200)* %c1, i64 %ashr
  ret i32 addrspace(200)* %gep
}
