; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -expandmemcmp -mtriple=aarch64-none-elf -mattr=+c64,+morello -target-abi purecap < %s | FileCheck %s

declare i32 @memcmp(ptr addrspace(200) nocapture, ptr addrspace(200) nocapture, i64)

define i32 @cmp2(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp2(
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = call i16 @llvm.bswap.i16(i16 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.bswap.i16(i16 [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = zext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP6:%.*]] = zext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = sub i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    ret i32 [[TMP7]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 2)
  ret i32 %call
}

define i32 @cmp3(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp3(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i16 [[TMP5:%.*]], [[TMP6:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i16 @llvm.bswap.i16(i16 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i16 @llvm.bswap.i16(i16 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i16 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1:%.*]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = zext i8 [[TMP10]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = zext i8 [[TMP11]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = sub i32 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br label [[ENDBLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ [[TMP14]], [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 3)
  ret i32 %call
}

define i32 @cmp4(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp4(
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.bswap.i32(i32 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.bswap.i32(i32 [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ugt i32 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ult i32 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = zext i1 [[TMP5]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = zext i1 [[TMP6]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = sub i32 [[TMP7]], [[TMP8]]
; CHECK-NEXT:    ret i32 [[TMP9]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 4)
  ret i32 %call
}

define i32 @cmp5(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp5(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[TMP5:%.*]], [[TMP6:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i32 @llvm.bswap.i32(i32 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i32 @llvm.bswap.i32(i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1:%.*]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = zext i8 [[TMP10]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = zext i8 [[TMP11]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = sub i32 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br label [[ENDBLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ [[TMP14]], [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 5)
  ret i32 %call
}

define i32 @cmp6(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp6(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i32 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP14:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i32 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP15:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i32 @llvm.bswap.i32(i32 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i32 @llvm.bswap.i32(i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = call i16 @llvm.bswap.i16(i16 [[TMP10]])
; CHECK-NEXT:    [[TMP13:%.*]] = call i16 @llvm.bswap.i16(i16 [[TMP11]])
; CHECK-NEXT:    [[TMP14]] = zext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[TMP15]] = zext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq i32 [[TMP14]], [[TMP15]]
; CHECK-NEXT:    br i1 [[TMP16]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 6)
  ret i32 %call
}

define i32 @cmp7(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp7(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i32 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP12:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i32 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP13:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i32 @llvm.bswap.i32(i32 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i32 @llvm.bswap.i32(i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 3
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 3
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12]] = call i32 @llvm.bswap.i32(i32 [[TMP10]])
; CHECK-NEXT:    [[TMP13]] = call i32 @llvm.bswap.i32(i32 [[TMP11]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i32 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 7)
  ret i32 %call
}

define i32 @cmp8(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp8(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.bswap.i64(i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.bswap.i64(i64 [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ugt i64 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ult i64 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = zext i1 [[TMP5]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = zext i1 [[TMP6]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = sub i32 [[TMP7]], [[TMP8]]
; CHECK-NEXT:    ret i32 [[TMP9]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 8)
  ret i32 %call
}

define i32 @cmp9(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp9(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[TMP5:%.*]], [[TMP6:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1:%.*]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = zext i8 [[TMP10]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = zext i8 [[TMP11]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = sub i32 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br label [[ENDBLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ [[TMP14]], [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 9)
  ret i32 %call
}

define i32 @cmp10(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp10(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP14:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP15:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = call i16 @llvm.bswap.i16(i16 [[TMP10]])
; CHECK-NEXT:    [[TMP13:%.*]] = call i16 @llvm.bswap.i16(i16 [[TMP11]])
; CHECK-NEXT:    [[TMP14]] = zext i16 [[TMP12]] to i64
; CHECK-NEXT:    [[TMP15]] = zext i16 [[TMP13]] to i64
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[TMP14]], [[TMP15]]
; CHECK-NEXT:    br i1 [[TMP16]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 10)
  ret i32 %call
}

define i32 @cmp11(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp11(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP12:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP13:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 3
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 3
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12]] = call i64 @llvm.bswap.i64(i64 [[TMP10]])
; CHECK-NEXT:    [[TMP13]] = call i64 @llvm.bswap.i64(i64 [[TMP11]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 11)
  ret i32 %call
}

define i32 @cmp12(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp12(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP14:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP15:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @llvm.bswap.i32(i32 [[TMP10]])
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @llvm.bswap.i32(i32 [[TMP11]])
; CHECK-NEXT:    [[TMP14]] = zext i32 [[TMP12]] to i64
; CHECK-NEXT:    [[TMP15]] = zext i32 [[TMP13]] to i64
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[TMP14]], [[TMP15]]
; CHECK-NEXT:    br i1 [[TMP16]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 12)
  ret i32 %call
}

define i32 @cmp13(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp13(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP12:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP13:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 5
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 5
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12]] = call i64 @llvm.bswap.i64(i64 [[TMP10]])
; CHECK-NEXT:    [[TMP13]] = call i64 @llvm.bswap.i64(i64 [[TMP11]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 13)
  ret i32 %call
}

define i32 @cmp14(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp14(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP12:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP13:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 6
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 6
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12]] = call i64 @llvm.bswap.i64(i64 [[TMP10]])
; CHECK-NEXT:    [[TMP13]] = call i64 @llvm.bswap.i64(i64 [[TMP11]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 14)
  ret i32 %call
}

define i32 @cmp15(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp15(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP12:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP13:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 7
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 7
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12]] = call i64 @llvm.bswap.i64(i64 [[TMP10]])
; CHECK-NEXT:    [[TMP13]] = call i64 @llvm.bswap.i64(i64 [[TMP11]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 15)
  ret i32 %call
}

define i32 @cmp16(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp16(
; CHECK-NEXT:    br label [[LOADBB:%.*]]
; CHECK:       res_block:
; CHECK-NEXT:    [[PHI_SRC1:%.*]] = phi i64 [ [[TMP5:%.*]], [[LOADBB]] ], [ [[TMP12:%.*]], [[LOADBB1:%.*]] ]
; CHECK-NEXT:    [[PHI_SRC2:%.*]] = phi i64 [ [[TMP6:%.*]], [[LOADBB]] ], [ [[TMP13:%.*]], [[LOADBB1]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[PHI_SRC1]], [[PHI_SRC2]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i32 -1, i32 1
; CHECK-NEXT:    br label [[ENDBLOCK:%.*]]
; CHECK:       loadbb:
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP5]] = call i64 @llvm.bswap.i64(i64 [[TMP3]])
; CHECK-NEXT:    [[TMP6]] = call i64 @llvm.bswap.i64(i64 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[LOADBB1]], label [[RES_BLOCK:%.*]]
; CHECK:       loadbb1:
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr addrspace(200) [[TMP8]], align 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr addrspace(200) [[TMP9]], align 1
; CHECK-NEXT:    [[TMP12]] = call i64 @llvm.bswap.i64(i64 [[TMP10]])
; CHECK-NEXT:    [[TMP13]] = call i64 @llvm.bswap.i64(i64 [[TMP11]])
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[ENDBLOCK]], label [[RES_BLOCK]]
; CHECK:       endblock:
; CHECK-NEXT:    [[PHI_RES:%.*]] = phi i32 [ 0, [[LOADBB1]] ], [ [[TMP2]], [[RES_BLOCK]] ]
; CHECK-NEXT:    ret i32 [[PHI_RES]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 16)
  ret i32 %call
}

define i32 @cmp_eq2(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq2(
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne i16 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = zext i1 [[TMP3]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP4]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 2)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq3(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq3(
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i16 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 2
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 2
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i8 [[TMP6]] to i16
; CHECK-NEXT:    [[TMP9:%.*]] = zext i8 [[TMP7]] to i16
; CHECK-NEXT:    [[TMP10:%.*]] = xor i16 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i16 [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ne i16 [[TMP11]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 3)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq4(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq4(
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = zext i1 [[TMP3]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP4]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 4)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq5(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq5(
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i8 [[TMP6]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = zext i8 [[TMP7]] to i32
; CHECK-NEXT:    [[TMP10:%.*]] = xor i32 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i32 [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ne i32 [[TMP11]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 5)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq6(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq6(
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i16 [[TMP6]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = zext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[TMP10:%.*]] = xor i32 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i32 [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ne i32 [[TMP11]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 6)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq7(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq7(
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 3
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 3
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = xor i32 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i32 [[TMP3]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i32 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 7)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq8(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq8(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = zext i1 [[TMP3]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP4]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 8)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq9(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq9(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i8 [[TMP6]] to i64
; CHECK-NEXT:    [[TMP9:%.*]] = zext i8 [[TMP7]] to i64
; CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i64 [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ne i64 [[TMP11]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 9)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq10(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq10(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i16 [[TMP6]] to i64
; CHECK-NEXT:    [[TMP9:%.*]] = zext i16 [[TMP7]] to i64
; CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i64 [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ne i64 [[TMP11]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 10)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq11(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq11(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 3
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 3
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = xor i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i64 [[TMP3]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i64 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 11)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq12(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq12(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i32 [[TMP6]] to i64
; CHECK-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP7]] to i64
; CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i64 [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ne i64 [[TMP11]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 12)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq13(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq13(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 5
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 5
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = xor i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i64 [[TMP3]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i64 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 13)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq14(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq14(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = xor i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i64 [[TMP3]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i64 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 14)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq15(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq15(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 7
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 7
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = xor i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i64 [[TMP3]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i64 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 15)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @cmp_eq16(ptr addrspace(200) nocapture readonly %x, ptr addrspace(200) nocapture readonly %y)  {
; CHECK-LABEL: @cmp_eq16(
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(200) [[X:%.*]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(200) [[Y:%.*]], align 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr addrspace(200) [[X]], i64 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(200) [[Y]], i64 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = xor i64 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = or i64 [[TMP3]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i64 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
; CHECK-NEXT:    ret i32 [[CONV]]
;
  %call = tail call i32 @memcmp(ptr addrspace(200) %x, ptr addrspace(200) %y, i64 16)
  %cmp = icmp eq i32 %call, 0
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}
