; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -aa-pipeline=basic-aa -passes=gvn -mtriple=cheri-none-freebsd -target-abi purecap < %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200"

@.str = private unnamed_addr addrspace(200) constant [8 x i8] c"somedata", align 1

define i32 @testFun([2 x i8 addrspace(200)*] inreg %A.coerce) local_unnamed_addr {
; CHECK-LABEL: define i32 @testFun
; CHECK-SAME: ([2 x ptr addrspace(200)] inreg [[A_COERCE:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_SROA_1:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
; CHECK-NEXT:    [[A_COERCE_FCA_1_EXTRACT:%.*]] = extractvalue [2 x ptr addrspace(200)] [[A_COERCE]], 1
; CHECK-NEXT:    store ptr addrspace(200) [[A_COERCE_FCA_1_EXTRACT]], ptr addrspace(200) [[A_SROA_1]], align 16
; CHECK-NEXT:    [[A_SROA_1_0_A_SROA_1_0_A_SROA_1_16_:%.*]] = load i32, ptr addrspace(200) [[A_SROA_1]], align 16
; CHECK-NEXT:    [[A_SROA_1_4_N_SROA_RAW_IDX3:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[A_SROA_1]], i64 4
; CHECK-NEXT:    [[A_SROA_1_4_A_SROA_1_4_A_SROA_1_20_:%.*]] = load i32, ptr addrspace(200) [[A_SROA_1_4_N_SROA_RAW_IDX3]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[A_SROA_1_0_A_SROA_1_0_A_SROA_1_16_]], [[A_SROA_1_4_A_SROA_1_4_A_SROA_1_20_]]
; CHECK-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @g(ptr addrspace(200) @.str)
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ -1, [[IF_THEN]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %A.sroa.1 = alloca i8 addrspace(200)*, align 16, addrspace(200)
  %A.coerce.fca.1.extract = extractvalue [2 x i8 addrspace(200)*] %A.coerce, 1
  store i8 addrspace(200)* %A.coerce.fca.1.extract, i8 addrspace(200)* addrspace(200)* %A.sroa.1, align 16
  %A.sroa.1.0.m.sroa_cast1 = bitcast i8 addrspace(200)* addrspace(200)* %A.sroa.1 to i32 addrspace(200)*
  %A.sroa.1.0.A.sroa.1.0.A.sroa.1.16. = load i32, i32 addrspace(200)* %A.sroa.1.0.m.sroa_cast1, align 16
  %A.sroa.1.4.n.sroa_raw_cast2 = bitcast i8 addrspace(200)* addrspace(200)* %A.sroa.1 to i8 addrspace(200)*
  %A.sroa.1.4.n.sroa_raw_idx3 = getelementptr inbounds i8, i8 addrspace(200)* %A.sroa.1.4.n.sroa_raw_cast2, i64 4
  %A.sroa.1.4.n.sroa_cast4 = bitcast i8 addrspace(200)* %A.sroa.1.4.n.sroa_raw_idx3 to i32 addrspace(200)*
  %A.sroa.1.4.A.sroa.1.4.A.sroa.1.20. = load i32, i32 addrspace(200)* %A.sroa.1.4.n.sroa_cast4, align 4
  %cmp = icmp eq i32 %A.sroa.1.0.A.sroa.1.0.A.sroa.1.16., %A.sroa.1.4.A.sroa.1.4.A.sroa.1.20.
  br i1 %cmp, label %return, label %if.then

if.then:
  %call = tail call i32 @g(i8 addrspace(200)* getelementptr inbounds ([8 x i8], [8 x i8] addrspace(200)* @.str, i64 0, i64 0))
  br label %return

return:
  %retval.0 = phi i32 [ -1, %if.then ], [ 0, %entry ]
  ret i32 %retval.0
}

declare i32 @g(i8 addrspace(200)*)
