// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_purecap_cc1 -emit-llvm -std=c++11 -o - %s | %cheri_FileCheck %s

struct ints {
  int x;
  int y;
  int a;
  int b;
};

struct floats {
  float x;
  float y;
  float a;
  float b;
};

// CHECK-LABEL: @_Z21test_aggregate_recordR4ints(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_FLOATS:%.*]], align 4, addrspace(200)
// CHECK-NEXT:    [[TI_ADDR:%.*]] = alloca [[STRUCT_INTS:%.*]] addrspace(200)*, align 16, addrspace(200)
// CHECK-NEXT:    store [[STRUCT_INTS]] addrspace(200)* [[TI:%.*]], [[STRUCT_INTS]] addrspace(200)* addrspace(200)* [[TI_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load [[STRUCT_INTS]] addrspace(200)*, [[STRUCT_INTS]] addrspace(200)* addrspace(200)* [[TI_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast [[STRUCT_INTS]] addrspace(200)* [[TMP0]] to i8 addrspace(200)*
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast [[STRUCT_FLOATS]] addrspace(200)* [[RETVAL]] to i8 addrspace(200)*
// CHECK-NEXT:    call void @llvm.memcpy.p200i8.p200i8.i64(i8 addrspace(200)* align 4 [[TMP2]], i8 addrspace(200)* align 4 [[TMP1]], i64 16, i1 false)
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast [[STRUCT_FLOATS]] addrspace(200)* [[RETVAL]] to { i64, i64 } addrspace(200)*
// CHECK-NEXT:    [[TMP4:%.*]] = load { i64, i64 }, { i64, i64 } addrspace(200)* [[TMP3]], align 4
// CHECK-NEXT:    ret { i64, i64 } [[TMP4]]
//
floats test_aggregate_record(ints& ti) {
   return __builtin_bit_cast(floats, ti);
}
