; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=inline < %s | FileCheck %s
target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200"
target triple = "aarch64-none--elf"

$_Z8test_impIQPFiiiES0_Evv = comdat any
$_Z8test_impIM8MemFun03FizEFiQRS0_EEvv = comdat any
$_ZNSt3__18functionIFiiiEEC2IQPS1_vEET_ = comdat any
$_ZNSt3__18functionIFiiiEE6targetIQPS1_EEQPT_v = comdat any
$_ZN7CreatorIQPFiiiEE6createEv = comdat any

declare i32 @_Z3fooii(i32, i32)

define void @_Z9test_funcv() local_unnamed_addr {
; CHECK-LABEL: define void @_Z9test_funcv() local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pcc(i64 ptrtoint (ptr @_Z3fooii to i64))
; CHECK-NEXT:    [[TOBOOL_I_I_I:%.*]] = icmp eq ptr addrspace(200) [[TMP0]], null
; CHECK-NEXT:    br i1 [[TOBOOL_I_I_I]], label [[_ZNST3__18FUNCTIONIFIIIEEC2IQPS1_VEET__EXIT_I:%.*]], label [[IF_THEN_I_I:%.*]]
; CHECK:       if.then.i.i:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       _ZNSt3__18functionIFiiiEEC2IQPS1_vEET_.exit.i:
; CHECK-NEXT:    unreachable
; CHECK:       _Z8test_impIQPFiiiES0_Evv.exit:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @_Z8test_impIQPFiiiES0_Evv()
  ret void
}

declare ptr addrspace(200) @llvm.cheri.cap.from.pcc(i64)

define void @_Z8test_impIQPFiiiES0_Evv() local_unnamed_addr comdat {
; CHECK-LABEL: define void @_Z8test_impIQPFiiiES0_Evv() local_unnamed_addr comdat {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pcc(i64 ptrtoint (ptr @_Z3fooii to i64))
; CHECK-NEXT:    [[TOBOOL_I_I:%.*]] = icmp eq ptr addrspace(200) [[TMP0]], null
; CHECK-NEXT:    br i1 [[TOBOOL_I_I]], label [[_ZNST3__18FUNCTIONIFIIIEEC2IQPS1_VEET__EXIT:%.*]], label [[IF_THEN_I:%.*]]
; CHECK:       if.then.i:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       _ZNSt3__18functionIFiiiEEC2IQPS1_vEET_.exit:
; CHECK-NEXT:    unreachable
;
entry:
  %call2 = call ptr addrspace(200) @_ZN7CreatorIQPFiiiEE6createEv()
  call void @_ZNSt3__18functionIFiiiEEC2IQPS1_vEET_(ptr addrspace(200) nonnull %call2)
  unreachable
}

define void @_Z8test_impIM8MemFun03FizEFiQRS0_EEvv() local_unnamed_addr comdat {
; CHECK-LABEL: define void @_Z8test_impIM8MemFun03FizEFiQRS0_EEvv() local_unnamed_addr comdat {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    unreachable
;
entry:
  unreachable
}

declare void @llvm.trap()

define void @_ZNSt3__18functionIFiiiEEC2IQPS1_vEET_(ptr addrspace(200) %__f) unnamed_addr comdat align 2 {
; CHECK-LABEL: define void @_ZNSt3__18functionIFiiiEEC2IQPS1_vEET_
; CHECK-SAME: (ptr addrspace(200) [[__F:%.*]]) unnamed_addr comdat align 2 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TOBOOL_I:%.*]] = icmp eq ptr addrspace(200) [[__F]], null
; CHECK-NEXT:    br i1 [[TOBOOL_I]], label [[IF_END:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    call void @llvm.trap()
; CHECK-NEXT:    unreachable
; CHECK:       if.end:
; CHECK-NEXT:    ret void
;
entry:
  %tobool.i = icmp eq ptr addrspace(200) %__f, null
  br i1 %tobool.i, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  call void @llvm.trap()
  unreachable

if.end:                                           ; preds = %entry
  ret void
}

define void @_ZNSt3__18functionIFiiiEE6targetIQPS1_EEQPT_v() local_unnamed_addr comdat align 2 {
; CHECK-LABEL: define void @_ZNSt3__18functionIFiiiEE6targetIQPS1_EEQPT_v() local_unnamed_addr comdat align 2 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret void
;
entry:
  ret void
}

define ptr addrspace(200) @_ZN7CreatorIQPFiiiEE6createEv() local_unnamed_addr comdat align 2 {
; CHECK-LABEL: define ptr addrspace(200) @_ZN7CreatorIQPFiiiEE6createEv() local_unnamed_addr comdat align 2 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.from.pcc(i64 ptrtoint (ptr @_Z3fooii to i64))
; CHECK-NEXT:    ret ptr addrspace(200) [[TMP0]]
;
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.from.pcc(i64 ptrtoint (ptr @_Z3fooii to i64))
  ret ptr addrspace(200) %0
}
