; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -loop-reduce -S | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"

define i32 @test(ptr %In, i64 %N) {
; CHECK-LABEL: define i32 @test
; CHECK-SAME: (ptr [[IN:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_PREHEADER:%.*]]
; CHECK:       for.preheader:
; CHECK-NEXT:    [[LSR_IV2:%.*]] = phi i64 [ [[LSR_IV_NEXT3:%.*]], [[FOR_INC:%.*]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[COUNTUP:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[COUNTUP_NEXT:%.*]], [[FOR_INC]] ]
; CHECK-NEXT:    [[COUNTDOWN:%.*]] = phi i64 [ [[N]], [[ENTRY]] ], [ [[COUNTDOWN_NEXT:%.*]], [[FOR_INC]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[COUNTUP]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_INC]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[LSR_IV1:%.*]] = phi ptr [ [[IN]], [[FOR_BODY_PREHEADER]] ], [ [[SCEVGEP:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[COUNTDOWN]], [[FOR_BODY_PREHEADER]] ], [ [[LSR_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ACC_LOOP:%.*]] = phi i32 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[SCEVGEP4:%.*]] = getelementptr i8, ptr [[LSR_IV1]], i64 [[LSR_IV2]]
; CHECK-NEXT:    [[VAL1:%.*]] = load i32, ptr [[LSR_IV1]], align 4
; CHECK-NEXT:    [[VAL2:%.*]] = load i32, ptr [[SCEVGEP4]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[VAL1]], [[VAL2]]
; CHECK-NEXT:    [[ADD]] = add i32 [[MUL]], [[ACC_LOOP]]
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV]], -1
; CHECK-NEXT:    [[SCEVGEP]] = getelementptr i8, ptr [[LSR_IV1]], i64 4
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_INC_LOOPEXIT:%.*]], label [[FOR_BODY]]
; CHECK:       for.inc.loopexit:
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, [[FOR_PREHEADER]] ], [ [[ADD]], [[FOR_INC_LOOPEXIT]] ]
; CHECK-NEXT:    [[COUNTUP_NEXT]] = add i64 [[COUNTUP]], 1
; CHECK-NEXT:    [[COUNTDOWN_NEXT]] = add i64 [[COUNTDOWN]], -1
; CHECK-NEXT:    [[LSR_IV_NEXT3]] = add i64 [[LSR_IV2]], 4
; CHECK-NEXT:    [[EXITCOND36:%.*]] = icmp eq i64 [[COUNTUP_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND36]], label [[FOR_END:%.*]], label [[FOR_PREHEADER]]
; CHECK:       for.end:
; CHECK-NEXT:    ret i32 [[ACC]]
;
entry:
  br label %for.preheader

for.preheader:
  %countup = phi i64 [ 0, %entry ], [ %countup.next, %for.inc ]
  %countdown = phi i64 [ %N, %entry ], [ %countdown.next, %for.inc ]
  %cmp = icmp slt i64 %countup, %N
  br i1 %cmp, label %for.body, label %for.inc

for.body:
  %i = phi i64 [ %i.next, %for.body ], [ 0, %for.preheader ]
  %acc.loop = phi i32 [ %add, %for.body ], [ 0, %for.preheader ]
  %off = add i64 %i, %countup
  %arrayidx1 = getelementptr inbounds i32, ptr %In, i64 %i
  %arrayidx2 = getelementptr inbounds i32, ptr %In, i64 %off
  %val1 = load i32, ptr %arrayidx1, align 4
  %val2 = load i32, ptr %arrayidx2, align 4
  %mul = mul i32 %val1, %val2
  %add = add i32 %mul, %acc.loop
  %i.next = add i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %countdown
  br i1 %exitcond, label %for.inc, label %for.body

for.inc:
  %acc = phi i32 [ 0, %for.preheader ], [ %add, %for.body ]
  %countup.next = add i64 %countup, 1
  %countdown.next = add i64 %countdown, -1
  %exitcond36 = icmp eq i64 %countup.next, %N
  br i1 %exitcond36, label %for.end, label %for.preheader

for.end:
  ret i32 %acc
}
