; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-pointer-comparison.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - | FileCheck %s --check-prefix=PURECAP
; This series of tests serves two purposes.
; The first purpose is to check that we generate efficient code for all
; capability comparisons, conditional branches and conditional selects.
; The second purpose is to check that we generate code that honours the
; signedness of the IR (which is always unsigned when emitting IR for C
; langage-level pointers, whereas __intcap uses the signedness of the type).
; NGINX has a loop with (void*)-1 as a sentinel value which was never entered
; due to this bug.
; Original issue: https://github.com/CTSRD-CHERI/llvm/issues/199
; Fixed upstream in https://reviews.llvm.org/D70917
; (be15dfa88fb1ed94d12f374797f98ede6808f809)
;
; Original source code showing this surprising behaviour (for CHERI-MIPS):
; int
; main(void)
; {
;         void *a, *b;
;
;         a = (void *)0x12033091e;
;         b = (void *)0xffffffffffffffff;
;
;         if (a < b) {
;                 printf("ok\n");
;                 return (0);
;         }
;
;         printf("surprising result\n");
;         return (1);
; }
;
; Morello had a similar code generation issue for selects, where a less than
; generated a csel instruction using a singed predicate instead of the unsigned
; one:
; void *select_lt(void *p1, void *p2) {
;   return p1 < p2 ? p1 : p2;
; }
; See https://git.morello-project.org/morello/llvm-project/-/issues/22

define i32 @eq(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: eq:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, eq
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: eq:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, eq
; PURECAP-NEXT:    ret c30
  %cmp = icmp eq ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ne(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: ne:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, ne
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ne:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, ne
; PURECAP-NEXT:    ret c30
  %cmp = icmp ne ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ugt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: ugt:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, hi
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ugt:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, hi
; PURECAP-NEXT:    ret c30
  %cmp = icmp ugt ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @uge(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: uge:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, hs
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: uge:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, hs
; PURECAP-NEXT:    ret c30
  %cmp = icmp uge ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ult(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: ult:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, lo
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ult:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, lo
; PURECAP-NEXT:    ret c30
  %cmp = icmp ult ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ule(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: ule:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, ls
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ule:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, ls
; PURECAP-NEXT:    ret c30
  %cmp = icmp ule ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sgt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: sgt:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, gt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sgt:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, gt
; PURECAP-NEXT:    ret c30
  %cmp = icmp sgt ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sge(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: sge:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, ge
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sge:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, ge
; PURECAP-NEXT:    ret c30
  %cmp = icmp sge ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @slt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: slt:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, lt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: slt:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, lt
; PURECAP-NEXT:    ret c30
  %cmp = icmp slt ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sle(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: sle:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    cset w0, le
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sle:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    cset w0, le
; PURECAP-NEXT:    ret c30
  %cmp = icmp sle ptr addrspace(200) %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @eq_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: eq_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, #1 // =0x1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: eq_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, #1 // =0x1
; PURECAP-NEXT:    ret c30
  %cmp = icmp eq ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ne_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ne_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, wzr
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ne_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, wzr
; PURECAP-NEXT:    ret c30
  %cmp = icmp ne ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ugt_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ugt_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, wzr
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ugt_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, wzr
; PURECAP-NEXT:    ret c30
  %cmp = icmp ugt ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @uge_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: uge_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, #1 // =0x1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: uge_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, #1 // =0x1
; PURECAP-NEXT:    ret c30
  %cmp = icmp uge ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ult_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ult_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, wzr
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ult_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, wzr
; PURECAP-NEXT:    ret c30
  %cmp = icmp ult ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ule_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ule_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, #1 // =0x1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ule_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, #1 // =0x1
; PURECAP-NEXT:    ret c30
  %cmp = icmp ule ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sgt_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: sgt_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, wzr
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sgt_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, wzr
; PURECAP-NEXT:    ret c30
  %cmp = icmp sgt ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sge_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: sge_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, #1 // =0x1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sge_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, #1 // =0x1
; PURECAP-NEXT:    ret c30
  %cmp = icmp sge ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @slt_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: slt_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, wzr
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: slt_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, wzr
; PURECAP-NEXT:    ret c30
  %cmp = icmp slt ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sle_same(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: sle_same:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov w0, #1 // =0x1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sle_same:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    mov w0, #1 // =0x1
; PURECAP-NEXT:    ret c30
  %cmp = icmp sle ptr addrspace(200) %a, %a
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @eq_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: eq_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, eq
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: eq_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, eq
; PURECAP-NEXT:    ret c30
  %cmp = icmp eq ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ne_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ne_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, ne
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ne_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, ne
; PURECAP-NEXT:    ret c30
  %cmp = icmp ne ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ugt_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ugt_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, hi
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ugt_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, hi
; PURECAP-NEXT:    ret c30
  %cmp = icmp ugt ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @uge_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: uge_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, hs
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: uge_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, hs
; PURECAP-NEXT:    ret c30
  %cmp = icmp uge ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ult_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ult_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, lo
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ult_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, lo
; PURECAP-NEXT:    ret c30
  %cmp = icmp ult ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @ule_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: ule_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, ls
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: ule_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, ls
; PURECAP-NEXT:    ret c30
  %cmp = icmp ule ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sgt_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: sgt_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, gt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sgt_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, gt
; PURECAP-NEXT:    ret c30
  %cmp = icmp sgt ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sge_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: sge_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, ge
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sge_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, ge
; PURECAP-NEXT:    ret c30
  %cmp = icmp sge ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @slt_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: slt_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, lt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: slt_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, lt
; PURECAP-NEXT:    ret c30
  %cmp = icmp slt ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define i32 @sle_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: sle_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    cset w0, le
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: sle_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    cset w0, le
; PURECAP-NEXT:    ret c30
  %cmp = icmp sle ptr addrspace(200) %a, null
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}

define ptr addrspace(200) @select_eq(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_eq:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, eq
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_eq:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, eq
; PURECAP-NEXT:    ret c30
  %cmp = icmp eq ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ne(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ne:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, ne
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ne:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, ne
; PURECAP-NEXT:    ret c30
  %cmp = icmp ne ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ugt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ugt:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, hi
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ugt:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, hi
; PURECAP-NEXT:    ret c30
  %cmp = icmp ugt ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_uge(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_uge:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, hs
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_uge:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, hs
; PURECAP-NEXT:    ret c30
  %cmp = icmp uge ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ult(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ult:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, lo
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ult:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, lo
; PURECAP-NEXT:    ret c30
  %cmp = icmp ult ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ule(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ule:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, ls
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ule:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, ls
; PURECAP-NEXT:    ret c30
  %cmp = icmp ule ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_sgt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_sgt:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, gt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_sgt:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, gt
; PURECAP-NEXT:    ret c30
  %cmp = icmp sgt ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_sge(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_sge:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, ge
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_sge:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, ge
; PURECAP-NEXT:    ret c30
  %cmp = icmp sge ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_slt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_slt:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, lt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_slt:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, lt
; PURECAP-NEXT:    ret c30
  %cmp = icmp slt ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_sle(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_sle:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    csel c0, c0, c1, le
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_sle:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    csel c0, c0, c1, le
; PURECAP-NEXT:    ret c30
  %cmp = icmp sle ptr addrspace(200) %a, %b
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_eq_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_eq_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, eq
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_eq_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, eq
; PURECAP-NEXT:    ret c30
  %cmp = icmp eq ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ne_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ne_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, ne
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ne_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, ne
; PURECAP-NEXT:    ret c30
  %cmp = icmp ne ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ugt_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ugt_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, hi
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ugt_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, hi
; PURECAP-NEXT:    ret c30
  %cmp = icmp ugt ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_uge_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_uge_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, hs
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_uge_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, hs
; PURECAP-NEXT:    ret c30
  %cmp = icmp uge ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ult_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ult_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, lo
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ult_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, lo
; PURECAP-NEXT:    ret c30
  %cmp = icmp ult ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_ule_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_ule_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, ls
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_ule_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, ls
; PURECAP-NEXT:    ret c30
  %cmp = icmp ule ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_sgt_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_sgt_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, gt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_sgt_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, gt
; PURECAP-NEXT:    ret c30
  %cmp = icmp sgt ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_sge_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_sge_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, ge
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_sge_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, ge
; PURECAP-NEXT:    ret c30
  %cmp = icmp sge ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_slt_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_slt_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, lt
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_slt_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, lt
; PURECAP-NEXT:    ret c30
  %cmp = icmp slt ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

define ptr addrspace(200) @select_sle_null(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: select_sle_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    csel c0, c0, c1, le
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: select_sle_null:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    csel c0, c0, c1, le
; PURECAP-NEXT:    ret c30
  %cmp = icmp sle ptr addrspace(200) %a, null
  %cond = select i1 %cmp, ptr addrspace(200) %a, ptr addrspace(200) %b
  ret ptr addrspace(200) %cond
}

declare i32 @func1() nounwind
declare i32 @func2() nounwind

define i32 @branch_eq(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_eq:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.eq .LBB50_2
; HYBRID-NEXT:  // %bb.1: // %if.end
; HYBRID-NEXT:    b func2
; HYBRID-NEXT:  .LBB50_2: // %if.then
; HYBRID-NEXT:    b func1
;
; PURECAP-LABEL: branch_eq:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.eq .LBB50_2
; PURECAP-NEXT:  // %bb.1: // %if.end
; PURECAP-NEXT:    b func2
; PURECAP-NEXT:  .LBB50_2: // %if.then
; PURECAP-NEXT:    b func1
entry:
  %cmp = icmp eq ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ne(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_ne:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.eq .LBB51_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB51_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ne:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.eq .LBB51_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB51_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ne ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ugt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_ugt:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.ls .LBB52_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB52_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ugt:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.ls .LBB52_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB52_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ugt ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_uge(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_uge:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.lo .LBB53_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB53_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_uge:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.lo .LBB53_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB53_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp uge ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ult(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_ult:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.hs .LBB54_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB54_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ult:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.hs .LBB54_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB54_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ult ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ule(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_ule:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.hi .LBB55_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB55_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ule:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.hi .LBB55_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB55_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ule ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_sgt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_sgt:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.le .LBB56_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB56_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_sgt:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.le .LBB56_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB56_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp sgt ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_sge(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_sge:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.lt .LBB57_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB57_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_sge:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.lt .LBB57_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB57_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp sge ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_slt(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_slt:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.ge .LBB58_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB58_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_slt:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.ge .LBB58_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB58_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp slt ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_sle(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: branch_sle:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, x1
; HYBRID-NEXT:    b.gt .LBB59_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB59_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_sle:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, x1
; PURECAP-NEXT:    b.gt .LBB59_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB59_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp sle ptr addrspace(200) %a, %b
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_eq_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_eq_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cbz x0, .LBB60_2
; HYBRID-NEXT:  // %bb.1: // %if.end
; HYBRID-NEXT:    b func2
; HYBRID-NEXT:  .LBB60_2: // %if.then
; HYBRID-NEXT:    b func1
;
; PURECAP-LABEL: branch_eq_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cbz x0, .LBB60_2
; PURECAP-NEXT:  // %bb.1: // %if.end
; PURECAP-NEXT:    b func2
; PURECAP-NEXT:  .LBB60_2: // %if.then
; PURECAP-NEXT:    b func1
entry:
  %cmp = icmp eq ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ne_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_ne_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cbz x0, .LBB61_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB61_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ne_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cbz x0, .LBB61_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB61_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ne ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ugt_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_ugt_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.ls .LBB62_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB62_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ugt_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.ls .LBB62_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB62_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ugt ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_uge_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_uge_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.lo .LBB63_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB63_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_uge_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.lo .LBB63_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB63_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp uge ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ult_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_ult_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.hs .LBB64_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB64_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ult_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.hs .LBB64_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB64_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ult ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_ule_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_ule_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.hi .LBB65_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB65_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_ule_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.hi .LBB65_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB65_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp ule ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_sgt_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_sgt_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.le .LBB66_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB66_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_sgt_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.le .LBB66_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB66_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp sgt ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_sge_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_sge_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    tbnz x0, #63, .LBB67_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB67_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_sge_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    tbnz x0, #63, .LBB67_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB67_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp sge ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_slt_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_slt_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.ge .LBB68_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB68_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_slt_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.ge .LBB68_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB68_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp slt ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}

define i32 @branch_sle_null(ptr addrspace(200) %a) nounwind {
; HYBRID-LABEL: branch_sle_null:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    cmp x0, #0
; HYBRID-NEXT:    b.gt .LBB69_2
; HYBRID-NEXT:  // %bb.1: // %if.then
; HYBRID-NEXT:    b func1
; HYBRID-NEXT:  .LBB69_2: // %if.end
; HYBRID-NEXT:    b func2
;
; PURECAP-LABEL: branch_sle_null:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    cmp x0, #0
; PURECAP-NEXT:    b.gt .LBB69_2
; PURECAP-NEXT:  // %bb.1: // %if.then
; PURECAP-NEXT:    b func1
; PURECAP-NEXT:  .LBB69_2: // %if.end
; PURECAP-NEXT:    b func2
entry:
  %cmp = icmp sle ptr addrspace(200) %a, null
  br i1 %cmp, label %if.then, label %if.end
if.then:
  %retval1 = tail call i32 @func1()
  ret i32 %retval1
if.end:
  %retval2 = tail call i32 @func2()
  ret i32 %retval2
}
