; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-memfn-call.ll
; Check that we call memset_c/memmove_c/memcpy_c in hybrid mode.
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - | FileCheck %s --check-prefix=PURECAP
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 %s -o - | FileCheck %s --check-prefix=HYBRID
%struct.x = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32 }

declare void @llvm.memmove.p200.p200.i64(ptr addrspace(200) nocapture, ptr addrspace(200) nocapture readonly, i64, i1)
declare void @llvm.memset.p200.i64(ptr addrspace(200) nocapture, i8, i64, i1)
declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) nocapture, ptr addrspace(200) nocapture readonly, i64, i1)

define void @call_memset(ptr addrspace(200) align 4 %dst) nounwind {
; PURECAP-LABEL: call_memset:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    movi v0.2d, #0000000000000000
; PURECAP-NEXT:    str xzr, [c0, #32]
; PURECAP-NEXT:    stp q0, q0, [c0]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: call_memset:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    movi v0.2d, #0000000000000000
; HYBRID-NEXT:    stur xzr, [c0, #32]
; HYBRID-NEXT:    stur q0, [c0, #16]
; HYBRID-NEXT:    stur q0, [c0, #0]
; HYBRID-NEXT:    ret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 4 %dst, i8 0, i64 40, i1 false)
  ret void
}

define void @call_memcpy(ptr addrspace(200) align 4 %dst, ptr addrspace(200) align 4 %src) nounwind {
; PURECAP-LABEL: call_memcpy:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    str c30, [csp, #-16]! // 16-byte Folded Spill
; PURECAP-NEXT:    mov w2, #40 // =0x28
; PURECAP-NEXT:    bl memcpy
; PURECAP-NEXT:    ldr c30, [csp], #16 // 16-byte Folded Reload
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: call_memcpy:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; HYBRID-NEXT:    mov w2, #40 // =0x28
; HYBRID-NEXT:    bl memcpy_c
; HYBRID-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; HYBRID-NEXT:    ret
entry:
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 4 %dst, ptr addrspace(200) align 4 %src, i64 40, i1 false)
  ret void
}

define void @call_memmove(ptr addrspace(200) align 4 %dst, ptr addrspace(200) align 4 %src) nounwind {
; PURECAP-LABEL: call_memmove:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    str c30, [csp, #-16]! // 16-byte Folded Spill
; PURECAP-NEXT:    mov w2, #40 // =0x28
; PURECAP-NEXT:    bl memmove
; PURECAP-NEXT:    ldr c30, [csp], #16 // 16-byte Folded Reload
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: call_memmove:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; HYBRID-NEXT:    mov w2, #40 // =0x28
; HYBRID-NEXT:    bl memmove_c
; HYBRID-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; HYBRID-NEXT:    ret
entry:
  call void @llvm.memmove.p200.p200.i64(ptr addrspace(200) align 4 %dst, ptr addrspace(200) align 4 %src, i64 40, i1 false)
  ret void
}

