; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/constant-memcpy.ll
; CHERI-GENERIC-UTC: opt --function-signature
; RUN: opt -S -instcombine -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - | FileCheck %s
target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"

@.str = private unnamed_addr addrspace(200) constant [16 x i8] c"foofoofoofoofoo\00", align 16
@.str.1 = private unnamed_addr addrspace(200) constant [17 x i8] c"barbarbarbarbara\00", align 16
@.str.2 = private unnamed_addr addrspace(200) constant [18 x i8] c"bazbazbazbazbazaa\00", align 16
@.str.3 = private unnamed_addr addrspace(200) constant [19 x i8] c"bifbizbifbifbifbif\00", align 16
@.str.4 = private unnamed_addr addrspace(200) constant [4 x i8] c"biz\00", align 1

define void @func(i32 noundef %s, i8 addrspace(200)* nocapture noundef writeonly %c) local_unnamed_addr addrspace(200) {
; CHECK-LABEL: define {{[^@]+}}@func
; CHECK-SAME: (i32 noundef [[S:%.*]], i8 addrspace(200)* nocapture noundef writeonly [[C:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i32 [[S]], label [[SW_DEFAULT:%.*]] [
; CHECK-NEXT:    i32 0, label [[SW_EPILOG:%.*]]
; CHECK-NEXT:    i32 5, label [[SW_BB1:%.*]]
; CHECK-NEXT:    i32 8, label [[SW_BB2:%.*]]
; CHECK-NEXT:    i32 9, label [[SW_BB3:%.*]]
; CHECK-NEXT:    ]
; CHECK:       sw.bb1:
; CHECK-NEXT:    br label [[SW_EPILOG]]
; CHECK:       sw.bb2:
; CHECK-NEXT:    br label [[SW_EPILOG]]
; CHECK:       sw.bb3:
; CHECK-NEXT:    br label [[SW_EPILOG]]
; CHECK:       sw.default:
; CHECK-NEXT:    br label [[SW_EPILOG]]
; CHECK:       sw.epilog:
; CHECK-NEXT:    [[SZ_0:%.*]] = phi i64 [ 4, [[SW_DEFAULT]] ], [ 19, [[SW_BB3]] ], [ 18, [[SW_BB2]] ], [ 17, [[SW_BB1]] ], [ 16, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[STR_0:%.*]] = phi i8 addrspace(200)* [ getelementptr inbounds ([4 x i8], [4 x i8] addrspace(200)* @.str.4, i64 0, i64 0), [[SW_DEFAULT]] ], [ getelementptr inbounds ([19 x i8], [19 x i8] addrspace(200)* @.str.3, i64 0, i64 0), [[SW_BB3]] ], [ getelementptr inbounds ([18 x i8], [18 x i8] addrspace(200)* @.str.2, i64 0, i64 0), [[SW_BB2]] ], [ getelementptr inbounds ([17 x i8], [17 x i8] addrspace(200)* @.str.1, i64 0, i64 0), [[SW_BB1]] ], [ getelementptr inbounds ([16 x i8], [16 x i8] addrspace(200)* @.str, i64 0, i64 0), [[ENTRY]] ]
; CHECK-NEXT:    tail call void @llvm.memcpy.p200i8.p200i8.i64(i8 addrspace(200)* noundef nonnull align 1 dereferenceable(1) [[C]], i8 addrspace(200)* noundef nonnull align 1 dereferenceable(1) [[STR_0]], i64 [[SZ_0]], i1 false) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  switch i32 %s, label %sw.default [
  i32 0, label %sw.epilog
  i32 5, label %sw.bb1
  i32 8, label %sw.bb2
  i32 9, label %sw.bb3
  ]

sw.bb1:                                           ; preds = %entry
  br label %sw.epilog

sw.bb2:                                           ; preds = %entry
  br label %sw.epilog

sw.bb3:                                           ; preds = %entry
  br label %sw.epilog

sw.default:                                       ; preds = %entry
  br label %sw.epilog

sw.epilog:                                        ; preds = %entry, %sw.default, %sw.bb3, %sw.bb2, %sw.bb1
  %sz.0 = phi i64 [ 4, %sw.default ], [ 19, %sw.bb3 ], [ 18, %sw.bb2 ], [ 17, %sw.bb1 ], [ 16, %entry ]
  %str.0 = phi i8 addrspace(200)* [ getelementptr inbounds ([4 x i8], [4 x i8] addrspace(200)* @.str.4, i64 0, i64 0), %sw.default ], [ getelementptr inbounds ([19 x i8], [19 x i8] addrspace(200)* @.str.3, i64 0, i64 0), %sw.bb3 ], [ getelementptr inbounds ([18 x i8], [18 x i8] addrspace(200)* @.str.2, i64 0, i64 0), %sw.bb2 ], [ getelementptr inbounds ([17 x i8], [17 x i8] addrspace(200)* @.str.1, i64 0, i64 0), %sw.bb1 ], [ getelementptr inbounds ([16 x i8], [16 x i8] addrspace(200)* @.str, i64 0, i64 0), %entry ]
  tail call void @llvm.memcpy.p200i8.p200i8.i64(i8 addrspace(200)* noundef nonnull align 1 dereferenceable(1) %c, i8 addrspace(200)* noundef nonnull align 1 dereferenceable(1) %str.0, i64 %sz.0, i1 false)
  ret void
}

declare void @llvm.memcpy.p200i8.p200i8.i64(i8 addrspace(200)* noalias nocapture writeonly, i8 addrspace(200)* noalias nocapture readonly, i64, i1 immarg) addrspace(200)

; UTC_ARGS: --disable
; CHECK: attributes #[[ATTR2]] = { no_preserve_cheri_tags }
