; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/frameindex-arith.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - | FileCheck %s

; Check that we can fold the GEP (PTRADD) into the FrameIndex calculation
; rather than emitting two instructions.

; Contains an explicit @llvm.cheri.cap.bounds.set so CheriBoundAllocas sees the
; use as safe and doesn't interfere by inserting bounds on the FrameIndex
; before the GEP/PTRADD.
define void @foo() nounwind {
; CHECK-LABEL: foo:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sub csp, csp, #32
; CHECK-NEXT:    add c0, csp, #14
; CHECK-NEXT:    str c30, [csp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    add c0, c0, #1
; CHECK-NEXT:    scbnds c0, c0, #0 // =0
; CHECK-NEXT:    bl bar
; CHECK-NEXT:    ldr c30, [csp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    add csp, csp, #32
; CHECK-NEXT:    ret c30
  %x = alloca [2 x i8], align 1, addrspace(200)
  %x_plus_1 = getelementptr inbounds [2 x i8], ptr addrspace(200) %x, i64 0, i64 1
  %p = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %x_plus_1, i64 0)
  call void @bar(ptr addrspace(200) %p)
  ret void
}

declare void @bar(ptr addrspace(200))

declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200), i64)
