; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/nodemand.ll
; RUN: opt -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -cheri-cap-to-int -S -o - | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"

define i1 @load_ptr(i32 addrspace(200)* addrspace(200)* nocapture readonly %a) {
; CHECK-LABEL: define {{[^@]+}}@load_ptr
; CHECK-SAME: (i32 addrspace(200)* addrspace(200)* nocapture readonly [[A:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 addrspace(200)* addrspace(200)* [[A]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[DOTNARROWED]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %0 = load i32 addrspace(200)*, i32 addrspace(200)* addrspace(200)* %a, align 16
  %cmp = icmp eq i32 addrspace(200)* %0, null
  ret i1 %cmp
}

define i1 @gep(i32 addrspace(200)* addrspace(200)* nocapture readonly %aptr, i32 addrspace(200) *addrspace(200)* nocapture readonly %bptr) {
; CHECK-LABEL: define {{[^@]+}}@gep
; CHECK-SAME: (i32 addrspace(200)* addrspace(200)* nocapture readonly [[APTR:%.*]], i32 addrspace(200)* addrspace(200)* nocapture readonly [[BPTR:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 addrspace(200)* addrspace(200)* [[APTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[A_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 addrspace(200)* addrspace(200)* [[BPTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[B_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[A_NARROWED]], 8
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[TMP2]], [[B_NARROWED]]
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %a = load i32 addrspace(200)*, i32 addrspace(200)* addrspace(200)* %aptr, align 16
  %b = load i32 addrspace(200)*, i32 addrspace(200)* addrspace(200)* %bptr, align 16
  %arrayidx = getelementptr inbounds i32, i32 addrspace(200)* %a, i64 2
  %cmp = icmp eq i32 addrspace(200)* %arrayidx, %b
  ret i1 %cmp
}

define i1 @bitcast(i8 addrspace(200)* addrspace(200)* nocapture readonly %aptr, i32 addrspace(200) *addrspace(200)* nocapture readonly %bptr) {
; CHECK-LABEL: define {{[^@]+}}@bitcast
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[APTR:%.*]], i32 addrspace(200)* addrspace(200)* nocapture readonly [[BPTR:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[APTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[A_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 addrspace(200)* addrspace(200)* [[BPTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[B_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[A_NARROWED]], 2
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[TMP2]], [[B_NARROWED]]
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %a = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %aptr, align 16
  %b = load i32 addrspace(200)*, i32 addrspace(200)* addrspace(200)* %bptr, align 16
  %arrayidx = getelementptr inbounds i8, i8 addrspace(200)* %a, i64 2
  %0 = bitcast i8 addrspace(200)*  %arrayidx to i32 addrspace(200)*
  %cmp = icmp eq i32 addrspace(200)* %0, %b
  ret i1 %cmp
}

define i1 @freeze(i8 addrspace(200)* addrspace(200)* nocapture readonly %aptr, i32 addrspace(200)* addrspace(200)* %bptr) {
; CHECK-LABEL: define {{[^@]+}}@freeze
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[APTR:%.*]], i32 addrspace(200)* addrspace(200)* [[BPTR:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[APTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[A_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i32 addrspace(200)* addrspace(200)* [[BPTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[B_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[A_NARROWED]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = freeze i64 [[TMP2]]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[TMP2]], [[B_NARROWED]]
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %a = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %aptr, align 16
  %b = load i32 addrspace(200)*, i32 addrspace(200)* addrspace(200)* %bptr, align 16
  %arrayidx = getelementptr inbounds i8, i8 addrspace(200)* %a, i64 2
  %0 = bitcast i8 addrspace(200)* %arrayidx to i32 addrspace(200)*
  %fr = freeze i32 addrspace(200)* %0
  %cmp = icmp eq i32 addrspace(200)* %0, %b
  ret i1 %cmp
}

define i1 @sel(i32 %q, i8 addrspace(200)* addrspace(200)* nocapture readonly %aptr, i8 addrspace(200)* addrspace(200)* nocapture readonly %bptr) {
; CHECK-LABEL: define {{[^@]+}}@sel
; CHECK-SAME: (i32 [[Q:%.*]], i8 addrspace(200)* addrspace(200)* nocapture readonly [[APTR:%.*]], i8 addrspace(200)* addrspace(200)* nocapture readonly [[BPTR:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[APTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[A_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[BPTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[B_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP1]], align 16
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[Q]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TOBOOL_NOT]], i64 [[B_NARROWED]], i64 [[A_NARROWED]]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[TMP2]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %a = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %aptr, align 16
  %b = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %bptr, align 16
  %tobool.not = icmp eq i32 %q, 0
  %b.a = select i1 %tobool.not, i8 addrspace(200)* %b, i8 addrspace(200)* %a
  %cmp = icmp eq i8 addrspace(200)* %b.a, null
  ret i1 %cmp
}

define i1 @testphi(i32 addrspace(200)* addrspace(200)* %aptr) {
; CHECK-LABEL: define {{[^@]+}}@testphi
; CHECK-SAME: (i32 addrspace(200)* addrspace(200)* [[APTR:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32 addrspace(200)* addrspace(200)* [[APTR]] to i64 addrspace(200)*
; CHECK-NEXT:    [[A_NARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    br label [[WHILE_COND:%.*]]
; CHECK:       while.cond:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i64 [ [[A_NARROWED]], [[ENTRY:%.*]] ], [ [[TMP2:%.*]], [[WHILE_COND]] ]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @cond(i64 [[TMP1]])
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[CALL]], 0
; CHECK-NEXT:    [[TMP2]] = add i64 [[TMP1]], 16
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[WHILE_END:%.*]], label [[WHILE_COND]]
; CHECK:       while.end:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[TMP1]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %a = load i32 addrspace(200)*, i32 addrspace(200)* addrspace(200)* %aptr, align 16
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %a.addr.0 = phi i32 addrspace(200)* [ %a, %entry ], [ %add.ptr, %while.cond ]
  %0 = bitcast i32 addrspace(200)* %a.addr.0 to i8 addrspace(200)*
  %1 = tail call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %0)
  %call = tail call i32 @cond(i64 %1)
  %tobool.not = icmp eq i32 %call, 0
  %add.ptr = getelementptr inbounds i32, i32 addrspace(200)* %a.addr.0, i64 4
  br i1 %tobool.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  %cmp = icmp eq i32 addrspace(200)*  %a.addr.0 , null
  ret i1 %cmp
}

declare i32 @cond(i64)

declare i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)*)

define i1 @addrset(i8 addrspace(200)* addrspace(200)* nocapture readonly %c, i64 %val) {
; CHECK-LABEL: define {{[^@]+}}@addrset
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[C:%.*]], i64 [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[C]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[VAL]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %c, align 16
  %1 = tail call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* %0, i64 %val)
  %cmp = icmp eq i8 addrspace(200)*  %1 , null
  ret i1 %cmp
}

declare i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)*, i64)

define i1 @permsand(i8 addrspace(200)* addrspace(200)* nocapture readonly %c, i64 %val) {
; CHECK-LABEL: define {{[^@]+}}@permsand
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[C:%.*]], i64 [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[C]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[DOTNARROWED]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %c, align 16
  %1 = tail call i8 addrspace(200)* @llvm.cheri.cap.perms.and.i64(i8 addrspace(200)* %0, i64 %val)
  %cmp = icmp eq i8 addrspace(200)*  %1 , null
  ret i1 %cmp
}

declare i8 addrspace(200)* @llvm.cheri.cap.perms.and.i64(i8 addrspace(200)*, i64)

define i1 @boundsset(i8 addrspace(200)* addrspace(200)* nocapture readonly %c, i64 %val) {
; CHECK-LABEL: define {{[^@]+}}@boundsset
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[C:%.*]], i64 [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[C]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[DOTNARROWED]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %c, align 16
  %1 = tail call i8 addrspace(200)* @llvm.cheri.cap.bounds.set.i64(i8 addrspace(200)* %0, i64 %val)
  %cmp = icmp eq i8 addrspace(200)*  %1 , null
  ret i1 %cmp
}

declare i8 addrspace(200)* @llvm.cheri.cap.bounds.set.i64(i8 addrspace(200)*, i64)

define i1 @boundssetexact(i8 addrspace(200)* addrspace(200)* nocapture readonly %c, i64 %val) {
; CHECK-LABEL: define {{[^@]+}}@boundssetexact
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[C:%.*]], i64 [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[C]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i64 [[DOTNARROWED]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %c, align 16
  %1 = tail call i8 addrspace(200)* @llvm.cheri.cap.bounds.set.exact.i64(i8 addrspace(200)* %0, i64 %val)
  %cmp = icmp eq i8 addrspace(200)*  %1 , null
  ret i1 %cmp
}

declare i8 addrspace(200)* @llvm.cheri.cap.bounds.set.exact.i64(i8 addrspace(200)*, i64)

define i1 @capcmp(i8 addrspace(200)* addrspace(200)* nocapture readonly %a, i8 addrspace(200)* addrspace(200)* nocapture readonly %b) {
; CHECK-LABEL: define {{[^@]+}}@capcmp
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[A:%.*]], i8 addrspace(200)* addrspace(200)* nocapture readonly [[B:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[A]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[B]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED1:%.*]] = load i64, i64 addrspace(200)* [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[DOTNARROWED]], [[DOTNARROWED1]]
; CHECK-NEXT:    ret i1 [[TMP2]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %a, align 16
  %1 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %b, align 16
  %2 = icmp eq i8 addrspace(200)* %0, %1
  ret i1 %2
}

define i64 @addrget(i8 addrspace(200)* addrspace(200)* nocapture readonly %a) {
; CHECK-LABEL: define {{[^@]+}}@addrget
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[A:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[A]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    ret i64 [[DOTNARROWED]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %a, align 16
  %1 = tail call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %0)
  ret i64 %1
}

define i64 @capdiff(i8 addrspace(200)* addrspace(200)* nocapture readonly %a, i8 addrspace(200)* addrspace(200)* nocapture readonly %b) {
; CHECK-LABEL: define {{[^@]+}}@capdiff
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[A:%.*]], i8 addrspace(200)* addrspace(200)* nocapture readonly [[B:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[A]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[B]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED1:%.*]] = load i64, i64 addrspace(200)* [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 [[DOTNARROWED]], [[DOTNARROWED1]]
; CHECK-NEXT:    ret i64 [[TMP2]]
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %a, align 16
  %1 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %b, align 16
  %2 = tail call i64 @llvm.cheri.cap.diff.i64(i8 addrspace(200)* %0, i8 addrspace(200)* %1)
  ret i64 %2
}

declare i64 @llvm.cheri.cap.diff.i64(i8 addrspace(200)*, i8 addrspace(200)*)

declare i32 @bar()

define i32 @foo(i8 addrspace(200)* addrspace(200)* nocapture readonly %a) {
; CHECK-LABEL: define {{[^@]+}}@foo
; CHECK-SAME: (i8 addrspace(200)* addrspace(200)* nocapture readonly [[A:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8 addrspace(200)* addrspace(200)* [[A]] to i64 addrspace(200)*
; CHECK-NEXT:    [[DOTNARROWED:%.*]] = load i64, i64 addrspace(200)* [[TMP0]], align 16
; CHECK-NEXT:    [[CMP31:%.*]] = icmp slt i64 [[DOTNARROWED]], 22
; CHECK-NEXT:    br i1 [[CMP31]], label [[WHILE_BODY_PREHEADER:%.*]], label [[WHILE_END:%.*]]
; CHECK:       while.body.preheader:
; CHECK-NEXT:    br label [[WHILE_BODY:%.*]]
; CHECK:       while.body:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i64 [ [[AND:%.*]], [[WHILE_BODY]] ], [ [[DOTNARROWED]], [[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @bar()
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i64 [[TMP1]], 6
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[TMP1]], 6
; CHECK-NEXT:    [[AND]] = and i64 [[ADD]], 45055
; CHECK-NEXT:    [[CMP2:%.*]] = icmp slt i64 [[AND]], 22
; CHECK-NEXT:    br i1 [[CMP2]], label [[WHILE_BODY]], label [[WHILE_END_LOOPEXIT:%.*]]
; CHECK:       while.end.loopexit:
; CHECK-NEXT:    br label [[WHILE_END]]
; CHECK:       while.end:
; CHECK-NEXT:    ret i32 0
;
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %a, align 16
  %cmp3 = icmp slt i8 addrspace(200)* %0, getelementptr (i8, i8 addrspace(200)* null, i64 22)
  br i1 %cmp3, label %while.body.preheader, label %while.end

while.body.preheader:                             ; preds = %entry
  br label %while.body

while.body:                                       ; preds = %while.body.preheader, %while.body
  %b.04 = phi i8 addrspace(200)* [ %3, %while.body ], [ %0, %while.body.preheader ]
  %call = tail call i32 @bar()
  %1 = tail call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %b.04)
  %add = add nsw i64 %1, 6
  %2 = getelementptr i8, i8 addrspace(200)* %b.04, i64 6
  %and = and i64 %add, 45055
  %3 = tail call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* %2, i64 %and)
  %cmp = icmp slt i8 addrspace(200)* %3, getelementptr (i8, i8 addrspace(200)* null, i64 22)
  br i1 %cmp, label %while.body, label %while.end.loopexit

while.end.loopexit:                               ; preds = %while.body
  br label %while.end

while.end:                                        ; preds = %while.end.loopexit, %entry
  ret i32 0
}
