; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/null-derivation.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 -o - < %s | FileCheck %s --check-prefix=HYBRID

define i8 addrspace(200)* @foo(i32 %x) {
; PURECAP-LABEL: foo:
; PURECAP:       .Lfunc_begin0:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    mov w0, #42
; PURECAP-NEXT:    gcvalue x0, c0
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: foo:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    mov w0, #42
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
entry:
  ret i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 42)
}

define i8 addrspace(200)* @bat(i32 %x) {
; PURECAP-LABEL: bat:
; PURECAP:       .Lfunc_begin1:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    // kill: def $w0 killed $w0 def $x0
; PURECAP-NEXT:    sxtw x0, w0
; PURECAP-NEXT:    gcvalue x0, c0
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: bat:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    // kill: def $w0 killed $w0 def $x0
; HYBRID-NEXT:    sxtw x0, w0
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
entry:
  %conv = sext i32 %x to i64
  %0 = getelementptr i8, i8 addrspace(200)* null, i64 %conv
  ret i8 addrspace(200)* %0
}

define i8 addrspace(200)* @baz(i32 %x) {
; PURECAP-LABEL: baz:
; PURECAP:       .Lfunc_begin2:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    add w8, w0, #1 // =1
; PURECAP-NEXT:    sxtw x0, w8
; PURECAP-NEXT:    gcvalue x0, c0
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: baz:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    add w8, w0, #1 // =1
; HYBRID-NEXT:    sxtw x0, w8
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
entry:
  %add = add nsw i32 %x, 1
  %conv = sext i32 %add to i64
  %0 = getelementptr i8, i8 addrspace(200)* null, i64 %conv
  ret i8 addrspace(200)* %0
}

declare i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)*)

define i64 @bif(i8 addrspace(200)* addrspace(200)* nocapture readonly %y) {
; PURECAP-LABEL: bif:
; PURECAP:       .Lfunc_begin3:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    ldr c0, [c0, #0]
; PURECAP-NEXT:    gcvalue x0, c0
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: bif:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    ldur c0, [c0, #0]
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
entry:
  %0 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %y, align 16
  %1 = tail call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* %0)
  ret i64 %1
}

define i8 addrspace(200)* @baf(i64 %y) {
; PURECAP-LABEL: baf:
; PURECAP:       .Lfunc_begin4:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    // kill: def $x0 killed $x0 def $c0
; PURECAP-NEXT:    gcvalue x0, c0
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: baf:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    // kill: def $x0 killed $x0 def $c0
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
entry:
  %0 = getelementptr i8, i8 addrspace(200)* null, i64 %y
  ret i8 addrspace(200)* %0
}
