; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/ptradd-immediate.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 < %s | FileCheck %s --check-prefix=PURECAP
;; Hybrid baseline to compare against
; RUN: sed 's/addrspace(200)//g' %s | llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 | FileCheck %s --check-prefix=HYBRID

;; If both offsets are known to be non-negative it is safe to commute them and
;; use an immediate load.
define i32 @nneg_nneg(ptr addrspace(200) %p, i16 %x) {
; PURECAP-LABEL: nneg_nneg:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    // kill: def $w1 killed $w1 def $x1
; PURECAP-NEXT:    add c0, c0, w1, uxth #2
; PURECAP-NEXT:    ldr w0, [c0, #4]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: nneg_nneg:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    // kill: def $w1 killed $w1 def $x1
; HYBRID-NEXT:    add x8, x0, w1, uxth #2
; HYBRID-NEXT:    ldr w0, [x8, #4]
; HYBRID-NEXT:    ret
  %x.ext = zext i16 %x to i64
  %q = getelementptr [1 x i32], ptr addrspace(200) %p, i64 1, i64 %x.ext
  %ret = load i32, ptr addrspace(200) %q
  ret i32 %ret
}

;; If both offsets are known to be negative it is safe to commute them and use
;; an immediate load.
define i32 @neg_neg(ptr addrspace(200) %p, i16 %x) {
; PURECAP-LABEL: neg_neg:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    orr w8, w1, #0x1
; PURECAP-NEXT:    mov x9, xzr
; PURECAP-NEXT:    sub x8, x9, w8, uxth
; PURECAP-NEXT:    add c0, c0, x8, uxtx #2
; PURECAP-NEXT:    ldur w0, [c0, #-4]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: neg_neg:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    // kill: def $w1 killed $w1 def $x1
; HYBRID-NEXT:    and x8, x1, #0xfffe
; HYBRID-NEXT:    mov w9, #4 // =0x4
; HYBRID-NEXT:    lsr x8, x8, #1
; HYBRID-NEXT:    bfi x9, x8, #3, #15
; HYBRID-NEXT:    sub x8, x0, x9
; HYBRID-NEXT:    ldur w0, [x8, #-4]
; HYBRID-NEXT:    ret
  %x.ext = zext i16 %x to i64
  %x.pos = or i64 %x.ext, 1
  %x.neg = sub i64 0, %x.pos
  %q = getelementptr [1 x i32], ptr addrspace(200) %p, i64 -1, i64 %x.neg
  %ret = load i32, ptr addrspace(200) %q
  ret i32 %ret
}

;; If one offset is known to be non-negative and the other negative it is not in
;; general safe to commute them and use an immediate load.
define i32 @nneg_neg(ptr addrspace(200) %p, i16 %x) {
; PURECAP-LABEL: nneg_neg:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    // kill: def $w1 killed $w1 def $x1
; PURECAP-NEXT:    and x8, x1, #0xfffe
; PURECAP-NEXT:    mov w9, #4 // =0x4
; PURECAP-NEXT:    lsr x8, x8, #1
; PURECAP-NEXT:    mov w10, #4 // =0x4
; PURECAP-NEXT:    bfi x9, x8, #3, #15
; PURECAP-NEXT:    sub x8, x10, x9
; PURECAP-NEXT:    ldr w0, [c0, x8]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: nneg_neg:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    // kill: def $w1 killed $w1 def $x1
; HYBRID-NEXT:    and x8, x1, #0xfffe
; HYBRID-NEXT:    mov w9, #4 // =0x4
; HYBRID-NEXT:    lsr x8, x8, #1
; HYBRID-NEXT:    bfi x9, x8, #3, #15
; HYBRID-NEXT:    sub x8, x0, x9
; HYBRID-NEXT:    ldr w0, [x8, #4]
; HYBRID-NEXT:    ret
  %x.ext = zext i16 %x to i64
  %x.pos = or i64 %x.ext, 1
  %x.neg = sub i64 0, %x.pos
  %q = getelementptr [1 x i32], ptr addrspace(200) %p, i64 1, i64 %x.neg
  %ret = load i32, ptr addrspace(200) %q
  ret i32 %ret
}

;; If one offset is known to be non-negative and the other negative it is not in
;; general safe to commute them and use an immediate load.
define i32 @neg_nneg(ptr addrspace(200) %p, i16 %x) {
; PURECAP-LABEL: neg_nneg:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    // kill: def $w1 killed $w1 def $x1
; PURECAP-NEXT:    and x8, x1, #0xffff
; PURECAP-NEXT:    lsl x8, x8, #2
; PURECAP-NEXT:    sub x8, x8, #4
; PURECAP-NEXT:    ldr w0, [c0, x8]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: neg_nneg:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    // kill: def $w1 killed $w1 def $x1
; HYBRID-NEXT:    add x8, x0, w1, uxth #2
; HYBRID-NEXT:    ldur w0, [x8, #-4]
; HYBRID-NEXT:    ret
  %x.ext = zext i16 %x to i64
  %q = getelementptr [1 x i32], ptr addrspace(200) %p, i64 -1, i64 %x.ext
  %ret = load i32, ptr addrspace(200) %q
  ret i32 %ret
}

;; If we do not know the sign of one offset it is not in general safe to
;; commute them and use an immediate load.
define i32 @nneg_unknown(ptr addrspace(200) %p, i64 %x) {
; PURECAP-LABEL: nneg_unknown:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    lsl x8, x1, #2
; PURECAP-NEXT:    add x8, x8, #4
; PURECAP-NEXT:    ldr w0, [c0, x8]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: nneg_unknown:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    add x8, x0, x1, lsl #2
; HYBRID-NEXT:    ldr w0, [x8, #4]
; HYBRID-NEXT:    ret
  %q = getelementptr [1 x i32], ptr addrspace(200) %p, i64 1, i64 %x
  %ret = load i32, ptr addrspace(200) %q
  ret i32 %ret
}

;; If we do not know the sign of one offset it is not in general safe to
;; commute them and use an immediate load.
define i32 @neg_unknown(ptr addrspace(200) %p, i64 %x) {
; PURECAP-LABEL: neg_unknown:
; PURECAP:       // %bb.0:
; PURECAP-NEXT:    lsl x8, x1, #2
; PURECAP-NEXT:    sub x8, x8, #4
; PURECAP-NEXT:    ldr w0, [c0, x8]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: neg_unknown:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    add x8, x0, x1, lsl #2
; HYBRID-NEXT:    ldur w0, [x8, #-4]
; HYBRID-NEXT:    ret
  %q = getelementptr [1 x i32], ptr addrspace(200) %p, i64 -1, i64 %x
  %ret = load i32, ptr addrspace(200) %q
  ret i32 %ret
}
