; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/ptrtoint.ll
;; Check that we can correctly generate code for ptrtoint and perform simple folds
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 < %s | FileCheck %s
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 < %s | FileCheck %s --check-prefix=HYBRID

define internal i64 @ptrtoint(ptr addrspace(200) %cap) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint:
; CHECK:       // %bb.0:
; CHECK-NEXT:    gcvalue x0, c0
; CHECK-NEXT:    ret c30
;
; HYBRID-LABEL: ptrtoint:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
  %ret = ptrtoint ptr addrspace(200) %cap to i64
  ret i64 %ret
}

define internal i64 @ptrtoint_plus_const(ptr addrspace(200) %cap) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_plus_const:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add x0, x0, #2
; CHECK-NEXT:    ret c30
;
; HYBRID-LABEL: ptrtoint_plus_const:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    add x0, x0, #2
; HYBRID-NEXT:    ret
  %zero = ptrtoint ptr addrspace(200) %cap to i64
  %ret = add i64 %zero, 2
  ret i64 %ret
}

define internal i64 @ptrtoint_plus_var(ptr addrspace(200) %cap, i64 %add) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_plus_var:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add x0, x0, x1
; CHECK-NEXT:    ret c30
;
; HYBRID-LABEL: ptrtoint_plus_var:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    add x0, x0, x1
; HYBRID-NEXT:    ret
  %zero = ptrtoint ptr addrspace(200) %cap to i64
  %ret = add i64 %zero, %add
  ret i64 %ret
}

define internal i64 @ptrtoint_null() addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_null:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    gcvalue x0, c0
; CHECK-NEXT:    ret c30
;
; HYBRID-LABEL: ptrtoint_null:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov x0, xzr
; HYBRID-NEXT:    gcvalue x0, c0
; HYBRID-NEXT:    ret
  %ret = ptrtoint ptr addrspace(200) null to i64
  ret i64 %ret
}

define internal i64 @ptrtoint_null_plus_const() addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_null_plus_const:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    add x0, x0, #2
; CHECK-NEXT:    ret c30
;
; HYBRID-LABEL: ptrtoint_null_plus_const:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov x0, xzr
; HYBRID-NEXT:    add x0, x0, #2
; HYBRID-NEXT:    ret
  %zero = ptrtoint ptr addrspace(200) null to i64
  %ret = add i64 %zero, 2
  ret i64 %ret
}

define internal i64 @ptrtoint_null_plus_var(i64 %add) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_null_plus_var:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x1, xzr
; CHECK-NEXT:    add x0, x1, x0
; CHECK-NEXT:    ret c30
;
; HYBRID-LABEL: ptrtoint_null_plus_var:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    mov x1, xzr
; HYBRID-NEXT:    add x0, x1, x0
; HYBRID-NEXT:    ret
  %zero = ptrtoint ptr addrspace(200) null to i64
  %ret = add i64 %zero, %add
  ret i64 %ret
}
