; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/stackframe-intrinsics.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: sed 's/addrspace(200)/addrspace(0)/g' %s | llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 | FileCheck %s --check-prefix HYBRID
; Check that we can lower llvm.frameaddress/llvm.returnaddress

; Capability-Inspection Instructions

define dso_local ptr addrspace(200) @frameaddr() addrspace(200) nounwind {
; PURECAP-LABEL: frameaddr:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    sub csp, csp, #48
; PURECAP-NEXT:    stp c29, c30, [csp, #16] // 32-byte Folded Spill
; PURECAP-NEXT:    add c29, csp, #16
; PURECAP-NEXT:    mov c0, c29
; PURECAP-NEXT:    str c29, [csp, #0]
; PURECAP-NEXT:    ldp c29, c30, [csp, #16] // 32-byte Folded Reload
; PURECAP-NEXT:    add csp, csp, #48
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: frameaddr:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    sub sp, sp, #32
; HYBRID-NEXT:    stp x29, x30, [sp, #16] // 16-byte Folded Spill
; HYBRID-NEXT:    add x29, sp, #16
; HYBRID-NEXT:    mov x0, x29
; HYBRID-NEXT:    str x29, [sp]
; HYBRID-NEXT:    ldp x29, x30, [sp, #16] // 16-byte Folded Reload
; HYBRID-NEXT:    add sp, sp, #32
; HYBRID-NEXT:    ret
entry:
  %b = alloca ptr addrspace(200), align 16, addrspace(200)
  %0 = call ptr addrspace(200) @llvm.frameaddress.p200(i32 0)
  store ptr addrspace(200) %0, ptr addrspace(200) %b, align 16
  %1 = load ptr addrspace(200), ptr addrspace(200) %b, align 16
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @llvm.frameaddress.p200(i32 immarg) addrspace(200)

define dso_local ptr addrspace(200) @retaddr() addrspace(200) nounwind {
; PURECAP-LABEL: retaddr:
; PURECAP:       // %bb.0: // %entry
; PURECAP-NEXT:    sub csp, csp, #16
; PURECAP-NEXT:    mov c0, c30
; PURECAP-NEXT:    str c30, [csp], #16
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: retaddr:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    sub sp, sp, #32
; HYBRID-NEXT:    str x30, [sp, #16] // 8-byte Folded Spill
; HYBRID-NEXT:    hint #7
; HYBRID-NEXT:    mov x0, x30
; HYBRID-NEXT:    str x30, [sp]
; HYBRID-NEXT:    ldr x30, [sp, #16] // 8-byte Folded Reload
; HYBRID-NEXT:    add sp, sp, #32
; HYBRID-NEXT:    ret
entry:
  %b = alloca ptr addrspace(200), align 16, addrspace(200)
  %0 = call ptr addrspace(200) @llvm.returnaddress.p200(i32 0)
  store ptr addrspace(200) %0, ptr addrspace(200) %b, align 16
  %1 = load ptr addrspace(200), ptr addrspace(200) %b, align 16
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @llvm.returnaddress.p200(i32 immarg) addrspace(200)
