; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-address-get-opt.ll
; RUN: opt -S --passes=instcombine -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: opt -S --passes=instcombine -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+cap-mode,+f %s -o - | FileCheck %s --check-prefix=PURECAP

target datalayout = "e-m:e-pf200:64:64:64:32-p:32:32-i64:64-n32-S128-A200-P200-G200"


@a = addrspace(200) global [200 x i32] zeroinitializer, align 4

define i32 @foo() {
; HYBRID-LABEL: define i32 @foo
; HYBRID-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    ret i32 196
;
; PURECAP-LABEL: define i32 @foo
; PURECAP-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    ret i32 196
;
entry:
  %0 = call i32 @llvm.cheri.cap.address.get.i32(i8 addrspace(200)* bitcast (i32 addrspace(200)* getelementptr inbounds ([200 x i32], [200 x i32] addrspace(200)* @a, i64 0, i64 198) to i8 addrspace(200)*))
  %1 = call i32 @llvm.cheri.cap.address.get.i32(i8 addrspace(200)* bitcast (i32 addrspace(200)* getelementptr inbounds ([200 x i32], [200 x i32] addrspace(200)* @a, i64 0, i64 2) to i8 addrspace(200)*))
  %sub.ptr.sub = sub i32 %0, %1
  %sub.ptr.div = sdiv exact i32 %sub.ptr.sub, 4
  ret i32 %sub.ptr.div
}

declare i32 @llvm.cheri.cap.address.get.i32(i8 addrspace(200)*)

; Don't fold a subtract of cheri_cap_address_get to cap_diff.
define i32 @bar(i32 %i) {
; HYBRID-LABEL: define i32 @bar
; HYBRID-SAME: (i32 [[I:%.*]]) addrspace(200) #[[ATTR0]] {
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [200 x i32], ptr addrspace(200) @a, i32 0, i32 [[I]]
; HYBRID-NEXT:    [[TMP0:%.*]] = call i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) nonnull getelementptr inbounds ([200 x i32], ptr addrspace(200) @a, i32 0, i32 198))
; HYBRID-NEXT:    [[TMP1:%.*]] = call i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) nonnull [[ARRAYIDX]])
; HYBRID-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i32 [[TMP0]], [[TMP1]]
; HYBRID-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i32 [[SUB_PTR_SUB]], 2
; HYBRID-NEXT:    ret i32 [[SUB_PTR_DIV]]
;
; PURECAP-LABEL: define i32 @bar
; PURECAP-SAME: (i32 [[I:%.*]]) addrspace(200) #[[ATTR0]] {
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [200 x i32], ptr addrspace(200) @a, i32 0, i32 [[I]]
; PURECAP-NEXT:    [[TMP0:%.*]] = call i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) nonnull getelementptr inbounds ([200 x i32], ptr addrspace(200) @a, i32 0, i32 198))
; PURECAP-NEXT:    [[TMP1:%.*]] = call i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) nonnull [[ARRAYIDX]])
; PURECAP-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i32 [[TMP0]], [[TMP1]]
; PURECAP-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i32 [[SUB_PTR_SUB]], 2
; PURECAP-NEXT:    ret i32 [[SUB_PTR_DIV]]
;
entry:
  %arrayidx = getelementptr inbounds [200 x i32], [200 x i32] addrspace(200)* @a, i64 0, i32 %i
  %0 = call i32 @llvm.cheri.cap.address.get.i32(i8 addrspace(200)* bitcast (i32 addrspace(200)* getelementptr inbounds ([200 x i32], [200 x i32] addrspace(200)* @a, i64 0, i64 198) to i8 addrspace(200)*))
  %1 = bitcast i32 addrspace(200)* %arrayidx to i8 addrspace(200)*
  %2 = call i32 @llvm.cheri.cap.address.get.i32(i8 addrspace(200)* %1)
  %sub.ptr.sub = sub i32 %0, %2
  %sub.ptr.div = sdiv exact i32 %sub.ptr.sub, 4
  ret i32 %sub.ptr.div
}
