; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S --passes=instcombine -mtriple=arm64 -o - %s | FileCheck %s --implicit-check-not=must_preserve_cheri_tags

define void @baz(ptr %dst, ptr %src)  {
; CHECK-LABEL: define void @baz
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 1 dereferenceable(32) [[DST]], ptr noundef nonnull align 1 dereferenceable(32) [[SRC]], i64 32, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  %call.i = tail call ptr @__memcpy_chk(ptr %dst, ptr %src, i64 32, i64 32)
  ret void
}

define void @foo(ptr %dst, ptr %src, i32 %size)  {
; CHECK-LABEL: define void @foo
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 1 dereferenceable(32) [[DST]], ptr noundef nonnull align 1 dereferenceable(32) [[SRC]], i64 32, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  %call.i = tail call ptr @__memcpy_chk(ptr %dst, ptr %src, i64 32, i64 32)
  ret void
}

define void @bazmove(ptr %dst, ptr %src)  {
; CHECK-LABEL: define void @bazmove
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @llvm.memmove.p0.p0.i64(ptr noundef nonnull align 1 dereferenceable(32) [[DST]], ptr noundef nonnull align 1 dereferenceable(32) [[SRC]], i64 32, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  %call.i = tail call ptr @__memmove_chk(ptr %dst, ptr %src, i64 32, i64 32)
  ret void
}

define void @foomove(ptr %dst, ptr %src, i32 %size)  {
; CHECK-LABEL: define void @foomove
; CHECK-SAME: (ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @llvm.memmove.p0.p0.i64(ptr noundef nonnull align 1 dereferenceable(32) [[DST]], ptr noundef nonnull align 1 dereferenceable(32) [[SRC]], i64 32, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  %call.i = tail call ptr @__memmove_chk(ptr %dst, ptr %src, i64 32, i64 32)
  ret void
}

declare ptr @__memcpy_chk(ptr, ptr, i64, i64)
declare ptr @__memmove_chk(ptr, ptr, i64, i64)
declare i64 @llvm.objectsize.i64.p0(ptr, i1)
