; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -aa-pipeline=basic-aa -passes=gvn -o - %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none-unknown-elf"

%class.i = type { i8 }
%class.a.0 = type { fp128 }
%struct.A = type { i8 }


; GVN shouldn't try to coerce a fat pointer to a capability or the other way around.

; CHECK-LABEL: foo
define dso_local void @foo(i64 %h.coerce, [1 x fp128] %g.coerce) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: define dso_local void @foo
; CHECK-SAME: (i64 [[H_COERCE:%.*]], [1 x fp128] [[G_COERCE:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[REF_TMP_I:%.*]] = alloca [[CLASS_A_0:%.*]], align 16, addrspace(200)
; CHECK-NEXT:    [[G_SROA_0:%.*]] = alloca fp128, align 16, addrspace(200)
; CHECK-NEXT:    [[G_COERCE_FCA_0_EXTRACT:%.*]] = extractvalue [1 x fp128] [[G_COERCE]], 0
; CHECK-NEXT:    store fp128 [[G_COERCE_FCA_0_EXTRACT]], fp128 addrspace(200)* [[G_SROA_0]], align 16
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast [[CLASS_A_0]] addrspace(200)* [[REF_TMP_I]] to i8 addrspace(200)*
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast [[CLASS_A_0]] addrspace(200)* [[REF_TMP_I]] to i8 addrspace(200)* addrspace(200)*
; CHECK-NEXT:    [[G_SROA_0_0__SROA_CAST3:%.*]] = bitcast fp128 addrspace(200)* [[G_SROA_0]] to i8 addrspace(200)* addrspace(200)*
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast fp128 [[G_COERCE_FCA_0_EXTRACT]] to i128
; CHECK-NEXT:    [[G_SROA_0_0_G_SROA_0_0_:%.*]] = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* [[G_SROA_0_0__SROA_CAST3]], align 16, !tbaa [[TBAA1:![0-9]+]]
; CHECK-NEXT:    store i8 addrspace(200)* [[G_SROA_0_0_G_SROA_0_0_]], i8 addrspace(200)* addrspace(200)* [[TMP1]], align 16, !tbaa [[TBAA1]]
; CHECK-NEXT:    ret void
;
entry:
  %ref.tmp.i = alloca %class.a.0, align 16, addrspace(200)
  %g.sroa.0 = alloca fp128, align 16, addrspace(200)
  %g.coerce.fca.0.extract = extractvalue [1 x fp128] %g.coerce, 0
  store fp128 %g.coerce.fca.0.extract, fp128 addrspace(200)* %g.sroa.0, align 16
  %0 = bitcast %class.a.0 addrspace(200)* %ref.tmp.i to i8 addrspace(200)*
  %1 = bitcast %class.a.0 addrspace(200)* %ref.tmp.i to i8 addrspace(200)* addrspace(200)*
  %g.sroa.0.0..sroa_cast3 = bitcast fp128 addrspace(200)* %g.sroa.0 to i8 addrspace(200)* addrspace(200)*
  %2 = bitcast fp128 %g.coerce.fca.0.extract to i128
  %g.sroa.0.0.g.sroa.0.0. = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %g.sroa.0.0..sroa_cast3, align 16, !tbaa !2
  store i8 addrspace(200)* %g.sroa.0.0.g.sroa.0.0., i8 addrspace(200)* addrspace(200)* %1, align 16, !tbaa !2
  ret void
}

attributes #0 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+c64,+neon" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { argmemonly nounwind }
attributes #2 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+c64,+neon" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { nounwind }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"wchar_size", i32 4}
!2 = !{!3, !3, i64 0}
!3 = !{!"long double", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C++ TBAA"}
