; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=arm64 -mattr=+c64,+morello -target-abi purecap -o - %s | FileCheck %s

define i64 @ZSTD_compressBlock_lazy2_row(ptr addrspace(200) %arg) addrspace(200) nounwind {
; CHECK-LABEL: ZSTD_compressBlock_lazy2_row:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    mov c1, c0
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    prfm plil1strm, [c1]
; CHECK-NEXT:    ret c30
entry:
  tail call void @llvm.prefetch.p200(ptr addrspace(200) %arg, i32 0, i32 0, i32 0)
  ret i64 0
}

declare void @llvm.prefetch.p200(ptr addrspace(200) nocapture readonly, i32 immarg, i32 immarg, i32 immarg) addrspace(200)
