; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=instcombine -march=arm64 -mattr=+c64 -target-abi purecap -S -o - %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none--elf"

@.str = private unnamed_addr addrspace(200) constant [5 x i8] c"dsad\00", align 1

define void @fun(ptr addrspace(200) %tt) addrspace(200) {
; CHECK-LABEL: define void @fun
; CHECK-SAME: (ptr addrspace(200) [[TT:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 1 dereferenceable(5) [[TT]], ptr addrspace(200) noundef nonnull align 1 dereferenceable(5) @.str, i64 5, i1 false) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  %call = call ptr addrspace(200) @strcpy(ptr addrspace(200) %tt, ptr addrspace(200) @.str)
  ret void
}

declare ptr addrspace(200) @strcpy(ptr addrspace(200), ptr addrspace(200)) addrspace(200)
