; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+morello -verify-machineinstrs %s -o - | FileCheck %s

define void @i32_mode_C(i32 %0, ptr %1) {
; CHECK-LABEL: i32_mode_C:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str c0, [x1, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:C}, $0", "=*m,r"(ptr elementtype(ptr addrspace(200)) %1, i32 %0)
  ret void
}

define void @i32_mode_C_zero(ptr %0) {
; CHECK-LABEL: i32_mode_C_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str czr, [x0, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:C}, $0", "=*m,i"(ptr elementtype(ptr addrspace(200)) %0, i32 0)
  ret void
}

define void @i64_mode_C(i64 %0, ptr %1) {
; CHECK-LABEL: i64_mode_C:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str c0, [x1, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:C}, $0", "=*m,r"(ptr elementtype(ptr addrspace(200)) %1, i64 %0)
  ret void
}

define void @i64_mode_C_zero(ptr %0) {
; CHECK-LABEL: i64_mode_C_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str czr, [x0, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:C}, $0", "=*m,i"(ptr elementtype(ptr addrspace(200)) %0, i64 0)
  ret void
}

define void @cap_mode_w(ptr addrspace(200) %0, ptr %1) {
; CHECK-LABEL: cap_mode_w:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str w0, [x1]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:w}, $0", "=*m,C"(ptr elementtype(i32) %1, ptr addrspace(200) %0)
  ret void
}

define void @cap_mode_w_zero(ptr %0) {
; CHECK-LABEL: cap_mode_w_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str wzr, [x0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:w}, $0", "=*m,C"(ptr elementtype(i32) %0, ptr addrspace(200) null)
  ret void
}

define void @cap_mode_x(ptr addrspace(200) %0, ptr %1) {
; CHECK-LABEL: cap_mode_x:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str x0, [x1]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:x}, $0", "=*m,C"(ptr elementtype(i64) %1, ptr addrspace(200) %0)
  ret void
}

define void @cap_mode_x_zero(ptr %0) {
; CHECK-LABEL: cap_mode_x_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str xzr, [x0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:x}, $0", "=*m,C"(ptr elementtype(i64) %0, ptr addrspace(200) null)
  ret void
}

define void @cap_mode_C(ptr addrspace(200) %0, ptr %1) {
; CHECK-LABEL: cap_mode_C:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str c0, [x1, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:C}, $0", "=*m,C"(ptr elementtype(ptr addrspace(200)) %1, ptr addrspace(200) %0)
  ret void
}

define void @cap_mode_C_zero(ptr %0) {
; CHECK-LABEL: cap_mode_C_zero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    //APP
; CHECK-NEXT:    str czr, [x0, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
  tail call void asm "str ${1:C}, $0", "=*m,C"(ptr elementtype(ptr addrspace(200)) %0, ptr addrspace(200) null)
  ret void
}
