; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple=arm64 -mattr=+c64 -target-abi purecap -passes=instcombine < %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"

define i1 @test1(ptr addrspace(200) %x) {
; CHECK-LABEL: define i1 @test1
; CHECK-SAME: (ptr addrspace(200) [[X:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load i16, ptr addrspace(200) [[X]], align 4
; CHECK-NEXT:    [[OR:%.*]] = icmp eq i16 [[LOAD]], 17791
; CHECK-NEXT:    ret i1 [[OR]]
;
  %load = load i16, ptr addrspace(200) %x, align 4
  %trunc = trunc i16 %load to i8
  %cmp1 = icmp eq i8 %trunc, 127
  %and = and i16 %load, -256
  %cmp2 = icmp eq i16 %and, 17664
  %or = and i1 %cmp1, %cmp2
  ret i1 %or
}

define i1 @test2(ptr addrspace(200) %x) {
; CHECK-LABEL: define i1 @test2
; CHECK-SAME: (ptr addrspace(200) [[X:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load i16, ptr addrspace(200) [[X]], align 4
; CHECK-NEXT:    [[OR:%.*]] = icmp eq i16 [[LOAD]], 32581
; CHECK-NEXT:    ret i1 [[OR]]
;
  %load = load i16, ptr addrspace(200) %x, align 4
  %and = and i16 %load, -256
  %cmp1 = icmp eq i16 %and, 32512
  %trunc = trunc i16 %load to i8
  %cmp2 = icmp eq i8 %trunc, 69
  %or = and i1 %cmp1, %cmp2
  ret i1 %or
}
