; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=arm64 -mattr=+c64,+morello,+use-16-cap-regs -target-abi purecap \
; RUN:     -cheri-stack-bounds-analysis=none -o - %s | FileCheck %s

target datalayout = "e-m:e-i64:64-i128:128-n32:64-S128-pf200:128:128:128:64-A200-P200-G200"

declare void @foo() addrspace(200)
declare i32 @bar(ptr addrspace(200), ptr addrspace(200), ptr addrspace(200), ptr addrspace(200), ptr addrspace(200), ptr addrspace(200)) addrspace(200)
declare i32 @baz(i64, i32, i16, i8, double, float) addrspace(200)

define i32 @testStackVars(i32 %argc, ptr addrspace(200) %argv) addrspace(200) {
; CHECK-LABEL: testStackVars:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub csp, csp, #160
; CHECK-NEXT:    .cfi_def_cfa csp, -160
; CHECK-NEXT:    str c29, [csp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    stp c30, c28, [csp, #48] // 32-byte Folded Spill
; CHECK-NEXT:    stp c27, c26, [csp, #80] // 32-byte Folded Spill
; CHECK-NEXT:    stp c25, c24, [csp, #112] // 32-byte Folded Spill
; CHECK-NEXT:    str x19, [csp, #144] // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset w19, -16
; CHECK-NEXT:    .cfi_offset c24, -32
; CHECK-NEXT:    .cfi_offset c25, -48
; CHECK-NEXT:    .cfi_offset c26, -64
; CHECK-NEXT:    .cfi_offset c27, -80
; CHECK-NEXT:    .cfi_offset c28, -96
; CHECK-NEXT:    .cfi_offset c30, -112
; CHECK-NEXT:    .cfi_offset c29, -128
; CHECK-NEXT:    bl foo
; CHECK-NEXT:    add c0, csp, #152
; CHECK-NEXT:    add c1, csp, #28
; CHECK-NEXT:    scbnds c24, c0, #8 // =8
; CHECK-NEXT:    add c0, csp, #24
; CHECK-NEXT:    scbnds c26, c0, #2 // =2
; CHECK-NEXT:    add c0, csp, #20
; CHECK-NEXT:    scbnds c27, c0, #1 // =1
; CHECK-NEXT:    add c0, csp, #8
; CHECK-NEXT:    scbnds c28, c0, #8 // =8
; CHECK-NEXT:    add c0, csp, #4
; CHECK-NEXT:    scbnds c25, c1, #4 // =4
; CHECK-NEXT:    scbnds c29, c0, #4 // =4
; CHECK-NEXT:    mov c0, c24
; CHECK-NEXT:    mov c1, c25
; CHECK-NEXT:    mov c2, c26
; CHECK-NEXT:    mov c3, c27
; CHECK-NEXT:    mov c4, c28
; CHECK-NEXT:    mov c5, c29
; CHECK-NEXT:    str xzr, [c24]
; CHECK-NEXT:    str wzr, [c25]
; CHECK-NEXT:    strh wzr, [c26]
; CHECK-NEXT:    strb wzr, [c27]
; CHECK-NEXT:    str xzr, [c28]
; CHECK-NEXT:    str wzr, [c29]
; CHECK-NEXT:    bl bar
; CHECK-NEXT:    mov w19, w0
; CHECK-NEXT:    ldr x0, [c24]
; CHECK-NEXT:    ldr w1, [c25]
; CHECK-NEXT:    ldr d0, [c28]
; CHECK-NEXT:    ldr s1, [c29]
; CHECK-NEXT:    ldrb w3, [c27]
; CHECK-NEXT:    ldrh w2, [c26]
; CHECK-NEXT:    bl baz
; CHECK-NEXT:    ldp c25, c24, [csp, #112] // 32-byte Folded Reload
; CHECK-NEXT:    ldp c27, c26, [csp, #80] // 32-byte Folded Reload
; CHECK-NEXT:    ldp c30, c28, [csp, #48] // 32-byte Folded Reload
; CHECK-NEXT:    ldr c29, [csp, #32] // 16-byte Folded Reload
; CHECK-NEXT:    add w0, w19, w0
; CHECK-NEXT:    ldr x19, [csp, #144] // 8-byte Folded Reload
; CHECK-NEXT:    add csp, csp, #160
; CHECK-NEXT:    ret c30
entry:
  %long = alloca i64, align 8, addrspace(200)
  %int = alloca i32, align 4, addrspace(200)
  %short = alloca i16, align 2, addrspace(200)
  %byte = alloca i8, addrspace(200)
  %double = alloca double, align 8, addrspace(200)
  %float = alloca float, align 4, addrspace(200)
  call void @foo()
  store i64 0, ptr addrspace(200) %long, align 8
  store i32 0, ptr addrspace(200) %int, align 4
  store i16 0, ptr addrspace(200) %short, align 2
  store i8 0, ptr addrspace(200) %byte
  store double 0.0, ptr addrspace(200) %double, align 8
  store float 0.0, ptr addrspace(200) %float, align 4
  %rv1 = call i32 @bar(ptr addrspace(200) %long, ptr addrspace(200) %int, ptr addrspace(200) %short, ptr addrspace(200) %byte, ptr addrspace(200) %double, ptr addrspace(200) %float)
  %ll = load i64, ptr addrspace(200) %long, align 8
  %li = load i32, ptr addrspace(200) %int, align 4
  %lh = load i16, ptr addrspace(200) %short, align 2
  %lb = load i8, ptr addrspace(200) %byte
  %ld = load double, ptr addrspace(200) %double, align 8
  %lf = load float, ptr addrspace(200) %float, align 4
  %rv2 = call i32 @baz(i64 %ll, i32 %li, i16 %lh, i8 %lb, double %ld, float %lf)
  %rv = add i32 %rv1, %rv2
  ret i32 %rv
}
