; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals
; RUN: opt -instcombine %s -march=aarch64 -mattr=+morello,+c64 -target-abi purecap -o - -S | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"

define void @test_inline_bcopy(i8 addrspace(200)* %a, i8 addrspace(200)* %b) local_unnamed_addr addrspace(200) {
; CHECK-LABEL: @test_inline_bcopy(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.memmove.p200i8.p200i8.i64(i8 addrspace(200)* noundef nonnull align 1 dereferenceable(20) [[B:%.*]], i8 addrspace(200)* noundef nonnull align 1 dereferenceable(20) [[A:%.*]], i64 20, i1 false) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  call void @bcopy(i8 addrspace(200)* %a, i8 addrspace(200)* %b, i64 20)
  ret void
}

declare void @bcopy(i8 addrspace(200)* nocapture readonly, i8 addrspace(200)* nocapture writeonly, i64) local_unnamed_addr addrspace(200)
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { argmemonly nofree nounwind willreturn }
; CHECK: attributes #[[ATTR1]] = { must_preserve_cheri_tags }
;.
