; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=12 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-NOPIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-NOPIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=24 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-NOPIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=32 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-NOPIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=48 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-NOPIC-NOLE %s

; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=12 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-PIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-PIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=24 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-PIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=32 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-PIC-NOLE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -mattr=+morello-tgot-tls-compat -tls-size=48 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-NOLE,CHECK-PIC-NOLE %s

; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -tls-size=12 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-12,CHECK-NOPIC-LE-12 %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-24,CHECK-NOPIC-LE-24 %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -tls-size=24 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-24,CHECK-NOPIC-LE-24 %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -tls-size=32 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-32,CHECK-NOPIC-LE-32 %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap \
; RUN:     -cheri-tgot-tls -tls-size=48 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-48,CHECK-NOPIC-LE-48 %s

; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -tls-size=12 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-12,CHECK-PIC-LE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-24,CHECK-PIC-LE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -tls-size=24 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-24,CHECK-PIC-LE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -tls-size=32 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-32,CHECK-PIC-LE %s
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi=purecap -relocation-model=pic \
; RUN:     -cheri-tgot-tls -tls-size=48 < %s \
; RUN:     | FileCheck -check-prefixes=CHECK-LE-48,CHECK-PIC-LE %s

; Check that TLS symbols are lowered correctly based on the specified
; model. Make sure they're external to avoid them all being optimised to Local
; Exec for the executable.

@unspecified = external thread_local addrspace(200) global i32
@ld = external thread_local(localdynamic) addrspace(200) global i32
@ie = external thread_local(initialexec) addrspace(200) global i32
@le = external thread_local(localexec) addrspace(200) global i32


; No model specified

define i32 addrspace(200)* @f1() nounwind {
; CHECK-NOPIC-NOLE-LABEL: f1:
; CHECK-NOPIC-NOLE:       .Lfunc_begin0:
; CHECK-NOPIC-NOLE-NEXT:  // %bb.0: // %entry
; CHECK-NOPIC-NOLE-NEXT:    adrp c8, :gottgot:unspecified
; CHECK-NOPIC-NOLE-NEXT:    ldr x8, [c8, :gottgot_lo12:unspecified]
; CHECK-NOPIC-NOLE-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-NOLE-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-NOLE-NEXT:    ret c30
;
; CHECK-PIC-NOLE-LABEL: f1:
; CHECK-PIC-NOLE:       .Lfunc_begin0:
; CHECK-PIC-NOLE-NEXT:  // %bb.0: // %entry
; CHECK-PIC-NOLE-NEXT:    str c30, [csp, #-16]! // 16-byte Folded Spill
; CHECK-PIC-NOLE-NEXT:    mrs c1, CTPIDR_EL0
; CHECK-PIC-NOLE-NEXT:    adrp c0, :tgot_tlsdesc:unspecified
; CHECK-PIC-NOLE-NEXT:    ldr c2, [c0, :tgot_tlsdesc_lo12:unspecified]
; CHECK-PIC-NOLE-NEXT:    add c0, c0, :tgot_tlsdesc_lo12:unspecified
; CHECK-PIC-NOLE-NEXT:    .tgot_tlsdesccall unspecified
; CHECK-PIC-NOLE-NEXT:    blr c2
; CHECK-PIC-NOLE-NEXT:    ldr c30, [csp], #16 // 16-byte Folded Reload
; CHECK-PIC-NOLE-NEXT:    ret c30
;
; CHECK-NOPIC-LE-12-LABEL: f1:
; CHECK-NOPIC-LE-12:       .Lfunc_begin0:
; CHECK-NOPIC-LE-12-NEXT:  // %bb.0: // %entry
; CHECK-NOPIC-LE-12-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-12-NEXT:    ldr c0, [c0, :tgot_lo12:unspecified]
; CHECK-NOPIC-LE-12-NEXT:    ret c30
;
; CHECK-NOPIC-LE-24-LABEL: f1:
; CHECK-NOPIC-LE-24:       .Lfunc_begin0:
; CHECK-NOPIC-LE-24-NEXT:  // %bb.0: // %entry
; CHECK-NOPIC-LE-24-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-24-NEXT:    add c0, c0, :tgot:unspecified, lsl #12
; CHECK-NOPIC-LE-24-NEXT:    ldr c0, [c0, :tgot_lo12_nc:unspecified]
; CHECK-NOPIC-LE-24-NEXT:    ret c30
;
; CHECK-NOPIC-LE-32-LABEL: f1:
; CHECK-NOPIC-LE-32:       .Lfunc_begin0:
; CHECK-NOPIC-LE-32-NEXT:  // %bb.0: // %entry
; CHECK-NOPIC-LE-32-NEXT:    movz x8, #:tgot_g1:unspecified
; CHECK-NOPIC-LE-32-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-32-NEXT:    movk x8, #:tgot_g0_nc:unspecified
; CHECK-NOPIC-LE-32-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-LE-32-NEXT:    ret c30
;
; CHECK-NOPIC-LE-48-LABEL: f1:
; CHECK-NOPIC-LE-48:       .Lfunc_begin0:
; CHECK-NOPIC-LE-48-NEXT:  // %bb.0: // %entry
; CHECK-NOPIC-LE-48-NEXT:    movz x8, #:tgot_g1:unspecified
; CHECK-NOPIC-LE-48-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-48-NEXT:    movk x8, #:tgot_g0_nc:unspecified
; CHECK-NOPIC-LE-48-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-LE-48-NEXT:    ret c30
;
; CHECK-PIC-LE-LABEL: f1:
; CHECK-PIC-LE:       .Lfunc_begin0:
; CHECK-PIC-LE-NEXT:  // %bb.0: // %entry
; CHECK-PIC-LE-NEXT:    str c30, [csp, #-16]! // 16-byte Folded Spill
; CHECK-PIC-LE-NEXT:    mrs c1, CTPIDR_EL0
; CHECK-PIC-LE-NEXT:    adrp c0, :tgot_tlsdesc:unspecified
; CHECK-PIC-LE-NEXT:    ldr c2, [c0, :tgot_tlsdesc_lo12:unspecified]
; CHECK-PIC-LE-NEXT:    add c0, c0, :tgot_tlsdesc_lo12:unspecified
; CHECK-PIC-LE-NEXT:    .tgot_tlsdesccall unspecified
; CHECK-PIC-LE-NEXT:    blr c2
; CHECK-PIC-LE-NEXT:    ldr c30, [csp], #16 // 16-byte Folded Reload
; CHECK-PIC-LE-NEXT:    ret c30
entry:
  ret i32 addrspace(200)* @unspecified
}


; localdynamic specified

define i32 addrspace(200)* @f2() nounwind {
; CHECK-NOPIC-NOLE-LABEL: f2:
; CHECK-NOPIC-NOLE:       .Lfunc_begin1:
; CHECK-NOPIC-NOLE-NEXT:  // %bb.0:
; CHECK-NOPIC-NOLE-NEXT:    adrp c8, :gottgot:ld
; CHECK-NOPIC-NOLE-NEXT:    ldr x8, [c8, :gottgot_lo12:ld]
; CHECK-NOPIC-NOLE-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-NOLE-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-NOLE-NEXT:    ret c30
;
; CHECK-PIC-NOLE-LABEL: f2:
; CHECK-PIC-NOLE:       .Lfunc_begin1:
; CHECK-PIC-NOLE-NEXT:  // %bb.0:
; CHECK-PIC-NOLE-NEXT:    str c30, [csp, #-16]! // 16-byte Folded Spill
; CHECK-PIC-NOLE-NEXT:    mrs c1, CTPIDR_EL0
; CHECK-PIC-NOLE-NEXT:    adrp c0, :tgot_tlsdesc:ld
; CHECK-PIC-NOLE-NEXT:    ldr c2, [c0, :tgot_tlsdesc_lo12:ld]
; CHECK-PIC-NOLE-NEXT:    add c0, c0, :tgot_tlsdesc_lo12:ld
; CHECK-PIC-NOLE-NEXT:    .tgot_tlsdesccall ld
; CHECK-PIC-NOLE-NEXT:    blr c2
; CHECK-PIC-NOLE-NEXT:    ldr c30, [csp], #16 // 16-byte Folded Reload
; CHECK-PIC-NOLE-NEXT:    ret c30
;
; CHECK-NOPIC-LE-12-LABEL: f2:
; CHECK-NOPIC-LE-12:       .Lfunc_begin1:
; CHECK-NOPIC-LE-12-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-12-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-12-NEXT:    ldr c0, [c0, :tgot_lo12:ld]
; CHECK-NOPIC-LE-12-NEXT:    ret c30
;
; CHECK-NOPIC-LE-24-LABEL: f2:
; CHECK-NOPIC-LE-24:       .Lfunc_begin1:
; CHECK-NOPIC-LE-24-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-24-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-24-NEXT:    add c0, c0, :tgot:ld, lsl #12
; CHECK-NOPIC-LE-24-NEXT:    ldr c0, [c0, :tgot_lo12_nc:ld]
; CHECK-NOPIC-LE-24-NEXT:    ret c30
;
; CHECK-NOPIC-LE-32-LABEL: f2:
; CHECK-NOPIC-LE-32:       .Lfunc_begin1:
; CHECK-NOPIC-LE-32-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-32-NEXT:    movz x8, #:tgot_g1:ld
; CHECK-NOPIC-LE-32-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-32-NEXT:    movk x8, #:tgot_g0_nc:ld
; CHECK-NOPIC-LE-32-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-LE-32-NEXT:    ret c30
;
; CHECK-NOPIC-LE-48-LABEL: f2:
; CHECK-NOPIC-LE-48:       .Lfunc_begin1:
; CHECK-NOPIC-LE-48-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-48-NEXT:    movz x8, #:tgot_g1:ld
; CHECK-NOPIC-LE-48-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-48-NEXT:    movk x8, #:tgot_g0_nc:ld
; CHECK-NOPIC-LE-48-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-LE-48-NEXT:    ret c30
;
; CHECK-PIC-LE-LABEL: f2:
; CHECK-PIC-LE:       .Lfunc_begin1:
; CHECK-PIC-LE-NEXT:  // %bb.0:
; CHECK-PIC-LE-NEXT:    str c30, [csp, #-16]! // 16-byte Folded Spill
; CHECK-PIC-LE-NEXT:    mrs c1, CTPIDR_EL0
; CHECK-PIC-LE-NEXT:    adrp c0, :tgot_tlsdesc:ld
; CHECK-PIC-LE-NEXT:    ldr c2, [c0, :tgot_tlsdesc_lo12:ld]
; CHECK-PIC-LE-NEXT:    add c0, c0, :tgot_tlsdesc_lo12:ld
; CHECK-PIC-LE-NEXT:    .tgot_tlsdesccall ld
; CHECK-PIC-LE-NEXT:    blr c2
; CHECK-PIC-LE-NEXT:    ldr c30, [csp], #16 // 16-byte Folded Reload
; CHECK-PIC-LE-NEXT:    ret c30
  ret i32 addrspace(200)* @ld
}


; initialexec specified

define i32 addrspace(200)* @f3() nounwind {
; CHECK-NOLE-LABEL: f3:
; CHECK-NOLE:       .Lfunc_begin2:
; CHECK-NOLE-NEXT:  // %bb.0:
; CHECK-NOLE-NEXT:    adrp c8, :gottgot:ie
; CHECK-NOLE-NEXT:    ldr x8, [c8, :gottgot_lo12:ie]
; CHECK-NOLE-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOLE-NEXT:    ldr c0, [c0, x8]
; CHECK-NOLE-NEXT:    ret c30
;
; CHECK-NOPIC-LE-12-LABEL: f3:
; CHECK-NOPIC-LE-12:       .Lfunc_begin2:
; CHECK-NOPIC-LE-12-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-12-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-12-NEXT:    ldr c0, [c0, :tgot_lo12:ie]
; CHECK-NOPIC-LE-12-NEXT:    ret c30
;
; CHECK-NOPIC-LE-24-LABEL: f3:
; CHECK-NOPIC-LE-24:       .Lfunc_begin2:
; CHECK-NOPIC-LE-24-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-24-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-24-NEXT:    add c0, c0, :tgot:ie, lsl #12
; CHECK-NOPIC-LE-24-NEXT:    ldr c0, [c0, :tgot_lo12_nc:ie]
; CHECK-NOPIC-LE-24-NEXT:    ret c30
;
; CHECK-NOPIC-LE-32-LABEL: f3:
; CHECK-NOPIC-LE-32:       .Lfunc_begin2:
; CHECK-NOPIC-LE-32-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-32-NEXT:    movz x8, #:tgot_g1:ie
; CHECK-NOPIC-LE-32-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-32-NEXT:    movk x8, #:tgot_g0_nc:ie
; CHECK-NOPIC-LE-32-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-LE-32-NEXT:    ret c30
;
; CHECK-NOPIC-LE-48-LABEL: f3:
; CHECK-NOPIC-LE-48:       .Lfunc_begin2:
; CHECK-NOPIC-LE-48-NEXT:  // %bb.0:
; CHECK-NOPIC-LE-48-NEXT:    movz x8, #:tgot_g1:ie
; CHECK-NOPIC-LE-48-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOPIC-LE-48-NEXT:    movk x8, #:tgot_g0_nc:ie
; CHECK-NOPIC-LE-48-NEXT:    ldr c0, [c0, x8]
; CHECK-NOPIC-LE-48-NEXT:    ret c30
;
; CHECK-PIC-LE-LABEL: f3:
; CHECK-PIC-LE:       .Lfunc_begin2:
; CHECK-PIC-LE-NEXT:  // %bb.0:
; CHECK-PIC-LE-NEXT:    adrp c8, :gottgot:ie
; CHECK-PIC-LE-NEXT:    ldr x8, [c8, :gottgot_lo12:ie]
; CHECK-PIC-LE-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-PIC-LE-NEXT:    ldr c0, [c0, x8]
; CHECK-PIC-LE-NEXT:    ret c30
  ret i32 addrspace(200)* @ie
}


; localexec specified

define i32 addrspace(200)* @f4() nounwind {
; CHECK-NOLE-LABEL: f4:
; CHECK-NOLE:       .Lfunc_begin3:
; CHECK-NOLE-NEXT:  // %bb.0:
; CHECK-NOLE-NEXT:    adrp c8, :gottgot:le
; CHECK-NOLE-NEXT:    ldr x8, [c8, :gottgot_lo12:le]
; CHECK-NOLE-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-NOLE-NEXT:    ldr c0, [c0, x8]
; CHECK-NOLE-NEXT:    ret c30
;
; CHECK-LE-12-LABEL: f4:
; CHECK-LE-12:       .Lfunc_begin3:
; CHECK-LE-12-NEXT:  // %bb.0:
; CHECK-LE-12-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-LE-12-NEXT:    ldr c0, [c0, :tgot_lo12:le]
; CHECK-LE-12-NEXT:    ret c30
;
; CHECK-LE-24-LABEL: f4:
; CHECK-LE-24:       .Lfunc_begin3:
; CHECK-LE-24-NEXT:  // %bb.0:
; CHECK-LE-24-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-LE-24-NEXT:    add c0, c0, :tgot:le, lsl #12
; CHECK-LE-24-NEXT:    ldr c0, [c0, :tgot_lo12_nc:le]
; CHECK-LE-24-NEXT:    ret c30
;
; CHECK-LE-32-LABEL: f4:
; CHECK-LE-32:       .Lfunc_begin3:
; CHECK-LE-32-NEXT:  // %bb.0:
; CHECK-LE-32-NEXT:    movz x8, #:tgot_g1:le
; CHECK-LE-32-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-LE-32-NEXT:    movk x8, #:tgot_g0_nc:le
; CHECK-LE-32-NEXT:    ldr c0, [c0, x8]
; CHECK-LE-32-NEXT:    ret c30
;
; CHECK-LE-48-LABEL: f4:
; CHECK-LE-48:       .Lfunc_begin3:
; CHECK-LE-48-NEXT:  // %bb.0:
; CHECK-LE-48-NEXT:    movz x8, #:tgot_g1:le
; CHECK-LE-48-NEXT:    mrs c0, CTPIDR_EL0
; CHECK-LE-48-NEXT:    movk x8, #:tgot_g0_nc:le
; CHECK-LE-48-NEXT:    ldr c0, [c0, x8]
; CHECK-LE-48-NEXT:    ret c30
  ret i32 addrspace(200)* @le
}
