; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=instcombine < %s -S -o - | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"

@a = common dso_local addrspace(200) global ptr addrspace(200) null, align 16

define dso_local i32 @foo() local_unnamed_addr addrspace(200) {
; CHECK-LABEL: define dso_local i32 @foo() local_unnamed_addr addrspace(200) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[MALLOC:%.*]] = call ptr addrspace(200) @malloc(i64 0)
; CHECK-NEXT:    store ptr addrspace(200) [[MALLOC]], ptr addrspace(200) @a, align 16
; CHECK-NEXT:    ret i32 undef
;
entry:
  %call = call ptr addrspace(200) @realloc(ptr addrspace(200) null, i64 0)
  store ptr addrspace(200) %call, ptr addrspace(200) @a, align 16
  ret i32 undef
}

declare ptr addrspace(200) @realloc(ptr addrspace(200), i64) addrspace(200)
