; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -march=aarch64 -mattr=+morello,+c64 -target-abi purecap -o - %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none-unknown-elf"


;----------------
; Generated from:
;
; uint64_t foo(uint64_t a0, uint64_t a1, uint64_t a2, uint64_t a3,
;              uint64_t a4, uint64_t a5, uint64_t a6, uint64_t a7) {
;   return a1 * a2 * a3 * a4 * a5 * a6 * a7 / a0;
; }
;
; Check that i64 args are passed on X0-X7
; and i64 return value is stored in X0.
;

define i64 @foo(i64 %a0, i64 %a1, i64 %a2, i64 %a3, i64 %a4, i64 %a5, i64 %a6, i64 %a7) addrspace(200) {
; CHECK-LABEL: foo:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mul x8, x2, x1
; CHECK-NEXT:    mul x8, x8, x3
; CHECK-NEXT:    mul x8, x8, x4
; CHECK-NEXT:    mul x8, x8, x5
; CHECK-NEXT:    mul x8, x8, x6
; CHECK-NEXT:    mul x8, x8, x7
; CHECK-NEXT:    udiv x0, x8, x0
; CHECK-NEXT:    ret c30
entry:
  %mul = mul i64 %a2, %a1
  %mul1 = mul i64 %mul, %a3
  %mul2 = mul i64 %mul1, %a4
  %mul3 = mul i64 %mul2, %a5
  %mul4 = mul i64 %mul3, %a6
  %mul5 = mul i64 %mul4, %a7
  %div = udiv i64 %mul5, %a0
  ret i64 %div
}


;----------------
; Generated from:
;
; __uint128_t quad_args(__uint128_t a0, __uint128_t a1, __uint128_t a2, __uint128_t a3) {
;   return a0 - a1 - a2 - a3;
; }
;
; Check that i128 args are passed on X0-X7
; and i128 return value is stored in X0,X1.
;
define i128 @quad_args(i128 %a0, i128 %a1, i128 %a2, i128 %a3) addrspace(200) {
; CHECK-LABEL: quad_args:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    subs x8, x0, x2
; CHECK-NEXT:    sbc x9, x1, x3
; CHECK-NEXT:    subs x8, x8, x4
; CHECK-NEXT:    sbc x9, x9, x5
; CHECK-NEXT:    subs x0, x8, x6
; CHECK-NEXT:    sbc x1, x9, x7
; CHECK-NEXT:    ret c30
entry:
  %sub = sub i128 %a0, %a1
  %sub1 = sub i128 %sub, %a2
  %sub2 = sub i128 %sub1, %a3
  ret i128 %sub2
}


;----------------
; Generated from:
;
; void bar(char *a0, char *a1, char *a2, char *a3,
;          char *a4, char *a5, char *a6, char *a7,
;          int n) {
;
;   a0[n] = a1[n+1] + a2[n+2] + a3[n+3] + a4[n+4] +
;           a5[n+5] + a6[n+6] + a7[n+7];
; }
;
; Check that pointer args are passed on C0-C7
; and additional args are passed on the stack.
;
define void @bar(ptr addrspace(200) %a0, ptr addrspace(200) %a1, ptr addrspace(200) %a2, ptr addrspace(200) %a3, ptr addrspace(200) %a4, ptr addrspace(200) %a5, ptr addrspace(200) %a6, ptr addrspace(200) %a7, i32 %n) addrspace(200) {
; CHECK-LABEL: bar:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    ldrsw x8, [csp]
; CHECK-NEXT:    add x9, x8, #1
; CHECK-NEXT:    add x10, x8, #2
; CHECK-NEXT:    add x11, x8, #3
; CHECK-NEXT:    add x12, x8, #4
; CHECK-NEXT:    add x13, x8, #5
; CHECK-NEXT:    add x14, x8, #6
; CHECK-NEXT:    add x15, x8, #7
; CHECK-NEXT:    ldrb w9, [c1, x9]
; CHECK-NEXT:    ldrb w10, [c2, x10]
; CHECK-NEXT:    ldrb w11, [c3, x11]
; CHECK-NEXT:    ldrb w12, [c4, x12]
; CHECK-NEXT:    ldrb w13, [c5, x13]
; CHECK-NEXT:    ldrb w14, [c6, x14]
; CHECK-NEXT:    add w9, w10, w9
; CHECK-NEXT:    ldrb w15, [c7, x15]
; CHECK-NEXT:    add w10, w11, w12
; CHECK-NEXT:    add w9, w9, w10
; CHECK-NEXT:    add w11, w13, w14
; CHECK-NEXT:    add w10, w11, w15
; CHECK-NEXT:    add w9, w9, w10
; CHECK-NEXT:    strb w9, [c0, x8]
; CHECK-NEXT:    ret c30
entry:
  %add = add nsw i32 %n, 1
  %idxprom = sext i32 %add to i64
  %arrayidx = getelementptr inbounds i8, ptr addrspace(200) %a1, i64 %idxprom
  %0 = load i8, ptr addrspace(200) %arrayidx, align 1
  %add1 = add nsw i32 %n, 2
  %idxprom2 = sext i32 %add1 to i64
  %arrayidx3 = getelementptr inbounds i8, ptr addrspace(200) %a2, i64 %idxprom2
  %1 = load i8, ptr addrspace(200) %arrayidx3, align 1
  %add5 = add i8 %1, %0
  %add6 = add nsw i32 %n, 3
  %idxprom7 = sext i32 %add6 to i64
  %arrayidx8 = getelementptr inbounds i8, ptr addrspace(200) %a3, i64 %idxprom7
  %2 = load i8, ptr addrspace(200) %arrayidx8, align 1
  %add10 = add i8 %add5, %2
  %add11 = add nsw i32 %n, 4
  %idxprom12 = sext i32 %add11 to i64
  %arrayidx13 = getelementptr inbounds i8, ptr addrspace(200) %a4, i64 %idxprom12
  %3 = load i8, ptr addrspace(200) %arrayidx13, align 1
  %add15 = add i8 %add10, %3
  %add16 = add nsw i32 %n, 5
  %idxprom17 = sext i32 %add16 to i64
  %arrayidx18 = getelementptr inbounds i8, ptr addrspace(200) %a5, i64 %idxprom17
  %4 = load i8, ptr addrspace(200) %arrayidx18, align 1
  %add20 = add i8 %add15, %4
  %add21 = add nsw i32 %n, 6
  %idxprom22 = sext i32 %add21 to i64
  %arrayidx23 = getelementptr inbounds i8, ptr addrspace(200) %a6, i64 %idxprom22
  %5 = load i8, ptr addrspace(200) %arrayidx23, align 1
  %add25 = add i8 %add20, %5
  %add26 = add nsw i32 %n, 7
  %idxprom27 = sext i32 %add26 to i64
  %arrayidx28 = getelementptr inbounds i8, ptr addrspace(200) %a7, i64 %idxprom27
  %6 = load i8, ptr addrspace(200) %arrayidx28, align 1
  %add30 = add i8 %add25, %6
  %idxprom32 = sext i32 %n to i64
  %arrayidx33 = getelementptr inbounds i8, ptr addrspace(200) %a0, i64 %idxprom32
  store i8 %add30, ptr addrspace(200) %arrayidx33, align 1
  ret void
}
