; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --no-generate-body-for-unused-prefixes
; RUN: llc < %s -mtriple=aarch64-none-elf -mattr=+c64,+morello -target-abi=purecap | FileCheck %s -implicit-check-not=.chericap --check-prefixes=CHECK,CHECK-NORMAL
; RUN: llc < %s -mtriple=aarch64-none-elf -mattr=+c64,+morello -target-abi=purecap-benchmark | FileCheck %s -implicit-check-not=.chericap --check-prefixes=CHECK,CHECK-BENCHMARK
; RUN: llc < %s -mtriple=aarch64-none-elf -mattr=+c64,+morello -target-abi=purecap -filetype=obj -o - \
; RUN:  | llvm-readobj --relocs --symbols - | FileCheck %s --check-prefixes=RELOCS,RELOCS-NORMAL
; RUN: llc < %s -mtriple=aarch64-none-elf -mattr=+c64,+morello -target-abi=purecap-benchmark -filetype=obj -o - \
; RUN:  | llvm-readobj --relocs --symbols - | FileCheck %s --check-prefixes=RELOCS,RELOCS-BENCHMARK

target triple = "aarch64-none--elf"

define dso_local ptr addrspace(200) @fun1() addrspace(200) nounwind {
; CHECK-NORMAL-LABEL: fun1:
; CHECK-NORMAL:       // %bb.0: // %entry
; CHECK-NORMAL-NEXT:    adrp c0, fun1
; CHECK-NORMAL-NEXT:    add c0, c0, :lo12:fun1
; CHECK-NORMAL-NEXT:    seal c0, c0, rb
; CHECK-NORMAL-NEXT:    ret c30
;
; CHECK-BENCHMARK-LABEL: fun1:
; CHECK-BENCHMARK:       // %bb.0: // %entry
; CHECK-BENCHMARK-NEXT:    adrp c0, fun1
; CHECK-BENCHMARK-NEXT:    add c0, c0, :lo12:fun1
; CHECK-BENCHMARK-NEXT:    seal c0, c0, rb
; CHECK-BENCHMARK-NEXT:    and x30, x30, #0xfffffffffffffffe
; CHECK-BENCHMARK-NEXT:    ret x30
entry:
  ret ptr addrspace(200) () addrspace(200)* @fun1
}

define ptr addrspace(200) @fun2() addrspace(200) nounwind {
; CHECK-NORMAL-LABEL: fun2:
; CHECK-NORMAL:       // %bb.0: // %entry
; CHECK-NORMAL-NEXT:  .Ltmp0: // Block address taken
; CHECK-NORMAL-NEXT:  // %bb.1: // %newb
; CHECK-NORMAL-NEXT:    adrp c0, .Ltmp0
; CHECK-NORMAL-NEXT:    add c0, c0, :lo12:.Ltmp0+1
; CHECK-NORMAL-NEXT:    seal c0, c0, rb
; CHECK-NORMAL-NEXT:    ret c30
;
; CHECK-BENCHMARK-LABEL: fun2:
; CHECK-BENCHMARK:       // %bb.0: // %entry
; CHECK-BENCHMARK-NEXT:  .Ltmp0: // Block address taken
; CHECK-BENCHMARK-NEXT:  // %bb.1: // %newb
; CHECK-BENCHMARK-NEXT:    adrp c0, .Ltmp0
; CHECK-BENCHMARK-NEXT:    add c0, c0, :lo12:.Ltmp0+1
; CHECK-BENCHMARK-NEXT:    seal c0, c0, rb
; CHECK-BENCHMARK-NEXT:    and x30, x30, #0xfffffffffffffffe
; CHECK-BENCHMARK-NEXT:    ret x30
entry:
  br label %newb
newb:
  ret ptr addrspace(200) blockaddress(@fun2, %newb)
}

define i64 @blockaddress_in_global() addrspace(200) nounwind {
; CHECK-NORMAL-LABEL: blockaddress_in_global:
; CHECK-NORMAL:       // %bb.0: // %entry
; CHECK-NORMAL-NEXT:    adrp c0, :got:addrof_label_in_global
; CHECK-NORMAL-NEXT:    ldr c0, [c0, :got_lo12:addrof_label_in_global]
; CHECK-NORMAL-NEXT:    ldr c0, [c0, #0]
; CHECK-NORMAL-NEXT:    br c0
; CHECK-NORMAL-NEXT:  .Ltmp1: // Block address taken
; CHECK-NORMAL-NEXT:  .LBB2_1: // %common.ret
; CHECK-NORMAL-NEXT:    mov w0, #2 // =0x2
; CHECK-NORMAL-NEXT:    ret c30
; CHECK-NORMAL-NEXT:  .Ltmp2: // Block address taken
; CHECK-NORMAL-NEXT:  .LBB2_2: // %label2
; CHECK-NORMAL-NEXT:    mov w0, #3 // =0x3
; CHECK-NORMAL-NEXT:    ret c30
;
; CHECK-BENCHMARK-LABEL: blockaddress_in_global:
; CHECK-BENCHMARK:       // %bb.0: // %entry
; CHECK-BENCHMARK-NEXT:    adrp c0, :got:addrof_label_in_global
; CHECK-BENCHMARK-NEXT:    ldr c0, [c0, :got_lo12:addrof_label_in_global]
; CHECK-BENCHMARK-NEXT:    ldr c0, [c0, #0]
; CHECK-BENCHMARK-NEXT:    br c0
; CHECK-BENCHMARK-NEXT:  .Ltmp1: // Block address taken
; CHECK-BENCHMARK-NEXT:  .LBB2_1: // %common.ret
; CHECK-BENCHMARK-NEXT:    mov w0, #2 // =0x2
; CHECK-BENCHMARK-NEXT:    and x30, x30, #0xfffffffffffffffe
; CHECK-BENCHMARK-NEXT:    ret x30
; CHECK-BENCHMARK-NEXT:  .Ltmp2: // Block address taken
; CHECK-BENCHMARK-NEXT:  .LBB2_2: // %label2
; CHECK-BENCHMARK-NEXT:    mov w0, #3 // =0x3
; CHECK-BENCHMARK-NEXT:    and x30, x30, #0xfffffffffffffffe
; CHECK-BENCHMARK-NEXT:    ret x30
entry:
  %0 = load ptr addrspace(200), ptr addrspace(200) @addrof_label_in_global, align 16
  br label %indirectgoto

label1:                                           ; preds = %indirectgoto
  ret i64 2

label2:                                           ; preds = %indirectgoto
  ret i64 3

indirectgoto:                                     ; preds = %entry
  %indirect.goto.dest = phi ptr addrspace(200) [ %0, %entry ]
  indirectbr ptr addrspace(200) %indirect.goto.dest, [label %label1, label %label2]
}

; Manual checks from here on:
; UTC_ARGS: --disable
@addrof_label_in_global = addrspace(200) global ptr addrspace(200) blockaddress(@blockaddress_in_global, %label1), align 16
; CHECK-LABEL: addrof_label_in_global:
; CHECK-NEXT:  .chericap .Lblockaddress_in_global$local+((.Ltmp1+1)-.Lblockaddress_in_global$local)
; CHECK-NEXT:  .size addrof_label_in_global, 16
@addrof_label_in_global_2 = addrspace(200) global ptr addrspace(200) blockaddress(@blockaddress_in_global, %label2), align 16
; CHECK-LABEL: addrof_label_in_global_2:
; CHECK-NEXT:  .chericap .Lblockaddress_in_global$local+((.Ltmp2+1)-.Lblockaddress_in_global$local)
; CHECK-NEXT:  .size addrof_label_in_global_2, 16


; All relocations are done againt blockaddress_in_global, so should have an
; even addend to make them C64 symbols (the final value is odd because of the
; LSB from blockaddress_in_global):
; RELOCS-LABEL: Relocations [
; RELOCS-LABEL: Section ({{.+}}) .rela.text {
; RELOCS-NEXT:    R_MORELLO_ADR_PREL_PG_HI20 fun1 0x0
; RELOCS-NEXT:    R_AARCH64_ADD_ABS_LO12_NC fun1 0x0
; RELOCS-NORMAL-NEXT:    R_MORELLO_ADR_PREL_PG_HI20 .text 0x10
; RELOCS-BENCHMARK-NEXT: R_MORELLO_ADR_PREL_PG_HI20 .text 0x14
;; Note: Extra addend since there is no symbol table entry with the LSB set
; RELOCS-NORMAL-NEXT:    R_AARCH64_ADD_ABS_LO12_NC .text 0x11
; RELOCS-BENCHMARK-NEXT: R_AARCH64_ADD_ABS_LO12_NC .text 0x15
; RELOCS-NEXT:    R_MORELLO_ADR_GOT_PAGE addrof_label_in_global 0x0
; RELOCS-NEXT:    R_MORELLO_LD128_GOT_LO12_NC addrof_label_in_global 0x0
; RELOCS-NEXT:  }
; RELOCS-LABEL: Section ({{.+}}) .rela.data {
;; Note: no extra addend since the symbol table already has the LSB set for
;; normal compilation, but for the benchmark ABI we have to set it explicitly
; RELOCS-NORMAL-NEXT:    0x0 R_MORELLO_CAPINIT .Lblockaddress_in_global$local 0x10
; RELOCS-BENCHMARK-NEXT: 0x0 R_MORELLO_CAPINIT .Lblockaddress_in_global$local 0x11
; RELOCS-NORMAL-NEXT:    0x10 R_MORELLO_CAPINIT .Lblockaddress_in_global$local 0x18
; RELOCS-BENCHMARK-NEXT: 0x10 R_MORELLO_CAPINIT .Lblockaddress_in_global$local 0x1D
; RELOCS-NEXT:  }
; RELOCS-LABEL: Symbols [
; RELOCS:  Symbol {
;; Ideally the LSB should be set in all relocation targets and we use .Ltmp0
;; as the target instead of .text+0x11.
; TODO:      Name: .Ltmp0 (
; TODO-NEXT: Value: 0x11{{$}}
; RELOCS:      Name: .Lblockaddress_in_global$local (
;; In the benchmark ABI the symbol value is not set with the LSB
; RELOCS-NORMAL-NEXT: Value: 0x21{{$}}
; RELOCS-BENCHMARK-NEXT: Value: 0x28{{$}}
; RELOCS:      Name: fun2 (
; RELOCS-NORMAL-NEXT: Value: 0x11{{$}}
; RELOCS-BENCHMARK-NEXT: Value: 0x14{{$}}
; RELOCS:      Name: blockaddress_in_global (
; RELOCS-NORMAL-NEXT: Value: 0x21{{$}}
; RELOCS-BENCHMARK-NEXT: Value: 0x28{{$}}
;; But the LSB should not be set in the data relocation targets
; RELOCS:      Name: addrof_label_in_global (
; RELOCS-NEXT: Value: 0x0{{$}}
; RELOCS:      Name: addrof_label_in_global_2 (
; RELOCS-NEXT: Value: 0x10{{$}}
