; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -mtriple=arm64 -mattr=+morello,+c64 -target-abi purecap -passes=instcombine -S -o - %s | FileCheck %s

; Don't crash while trying to simplify icmps with vectors of capabilities as operands.

target datalayout = "e-m:e-i64:64-i128:128-n32:64-S128-pf200:128:128:128:64-A200-P200-G200"

define <2 x i32> @foo(ptr addrspace(200) %con0,
; CHECK-LABEL: define <2 x i32> @foo
; CHECK-SAME: (ptr addrspace(200) [[CON0:%.*]], ptr addrspace(200) [[CON1:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[IN0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CON0]], align 16
; CHECK-NEXT:    [[IN1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CON1]], align 16
; CHECK-NEXT:    [[VEC0:%.*]] = insertelement <2 x ptr addrspace(200)> undef, ptr addrspace(200) [[IN0]], i64 0
; CHECK-NEXT:    [[VEC1:%.*]] = insertelement <2 x ptr addrspace(200)> [[VEC0]], ptr addrspace(200) [[IN1]], i64 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne <2 x ptr addrspace(200)> [[VEC1]], zeroinitializer
; CHECK-NEXT:    [[RET:%.*]] = zext <2 x i1> [[CMP]] to <2 x i32>
; CHECK-NEXT:    ret <2 x i32> [[RET]]
;
  ptr addrspace(200) %con1 ) addrspace(200) {
  %in0 = load ptr addrspace(200), ptr addrspace(200) %con0, align 16
  %in1 = load ptr addrspace(200), ptr addrspace(200) %con1, align 16
  %vec0 = insertelement <2 x ptr addrspace(200)> undef, ptr addrspace(200) %in0, i32 0
  %vec1 = insertelement <2 x ptr addrspace(200)> %vec0, ptr addrspace(200) %in1, i32 1
  %cmp = icmp ne <2 x ptr addrspace(200)> %vec1, zeroinitializer
  %ret = zext <2 x i1> %cmp to <2 x i32>
  ret <2 x i32> %ret
}
