; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+morello,+c64 -target-abi purecap %s -o - | FileCheck %s

define dso_local i8 addrspace(200)* @foo(i8 addrspace(200)* noundef readonly %ptr) {
; CHECK-LABEL: foo:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ldrb w8, [c0]
; CHECK-NEXT:    cmp w8, #0 // =0
; CHECK-NEXT:    cset w8, ne
; CHECK-NEXT:    add c0, c0, x8, uxtx
; CHECK-NEXT:    ret c30
entry:
  %0 = load i8, i8 addrspace(200)* %ptr, align 1
  %tobool.not = icmp ne i8 %0, 0
  %spec.select.idx = zext i1 %tobool.not to i64
  %spec.select = getelementptr i8, i8 addrspace(200)* %ptr, i64 %spec.select.idx
  ret i8 addrspace(200)* %spec.select
}

define dso_local i8 addrspace(200)* @bar(i64 %x, i8 addrspace(200)* noundef readonly %ptr) {
; CHECK-LABEL: bar:
; CHECK:       .Lfunc_begin1:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    cmp x0, #0 // =0
; CHECK-NEXT:    cset w8, ne
; CHECK-NEXT:    add c0, c1, x8, uxtx
; CHECK-NEXT:    ret c30
entry:
  %tobool.not = icmp ne i64 %x, 0
  %spec.select.idx = zext i1 %tobool.not to i64
  %spec.select = getelementptr i8, i8 addrspace(200)* %ptr, i64 %spec.select.idx
  ret i8 addrspace(200)* %spec.select
}

define dso_local i8 addrspace(200)* @baz(i8 addrspace(200)* %x, i8 addrspace(200)* noundef readonly %ptr) {
; CHECK-LABEL: baz:
; CHECK:       .Lfunc_begin2:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    cmp x0, #0 // =0
; CHECK-NEXT:    cset w8, ne
; CHECK-NEXT:    add c0, c1, x8, uxtx
; CHECK-NEXT:    ret c30
entry:
  %tobool.not = icmp ne i8 addrspace(200)* %x, null
  %spec.select.idx = zext i1 %tobool.not to i64
  %spec.select = getelementptr i8, i8 addrspace(200)* %ptr, i64 %spec.select.idx
  ret i8 addrspace(200)* %spec.select
}
