; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64 -mattr=+morello -o - %s | FileCheck %s

;; Capabilities are not callee-saved, so they don't get spilled.
define dso_local void @func(ptr addrspace(200) nocapture readnone %bb, ptr addrspace(200) %cc) local_unnamed_addr addrspace(200) {
; CHECK-LABEL: func:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp d15, d14, [sp, #-144]! // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 144
; CHECK-NEXT:    stp d13, d12, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    stp d11, d10, [sp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    stp d9, d8, [sp, #48] // 16-byte Folded Spill
; CHECK-NEXT:    stp x28, x27, [sp, #64] // 16-byte Folded Spill
; CHECK-NEXT:    stp x26, x25, [sp, #80] // 16-byte Folded Spill
; CHECK-NEXT:    stp x24, x23, [sp, #96] // 16-byte Folded Spill
; CHECK-NEXT:    stp x22, x21, [sp, #112] // 16-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #128] // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset w19, -8
; CHECK-NEXT:    .cfi_offset w20, -16
; CHECK-NEXT:    .cfi_offset w21, -24
; CHECK-NEXT:    .cfi_offset w22, -32
; CHECK-NEXT:    .cfi_offset w23, -40
; CHECK-NEXT:    .cfi_offset w24, -48
; CHECK-NEXT:    .cfi_offset w25, -56
; CHECK-NEXT:    .cfi_offset w26, -64
; CHECK-NEXT:    .cfi_offset w27, -72
; CHECK-NEXT:    .cfi_offset w28, -80
; CHECK-NEXT:    .cfi_offset b8, -88
; CHECK-NEXT:    .cfi_offset b9, -96
; CHECK-NEXT:    .cfi_offset b10, -104
; CHECK-NEXT:    .cfi_offset b11, -112
; CHECK-NEXT:    .cfi_offset b12, -120
; CHECK-NEXT:    .cfi_offset b13, -128
; CHECK-NEXT:    .cfi_offset b14, -136
; CHECK-NEXT:    .cfi_offset b15, -144
; CHECK-NEXT:    //APP
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ldp x20, x19, [sp, #128] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x22, x21, [sp, #112] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x24, x23, [sp, #96] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x26, x25, [sp, #80] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x28, x27, [sp, #64] // 16-byte Folded Reload
; CHECK-NEXT:    ldp d9, d8, [sp, #48] // 16-byte Folded Reload
; CHECK-NEXT:    ldp d11, d10, [sp, #32] // 16-byte Folded Reload
; CHECK-NEXT:    ldp d13, d12, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldp d15, d14, [sp], #144 // 16-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  call void asm sideeffect "", "~{x19},~{x20},~{x21},~{x22},~{x23},~{x24},~{x25},~{x26},~{x27},~{x28},~{d8},~{d9},~{d10},~{d11},~{d12},~{d13},~{d14},~{d15}"() nounwind
  ret void
}

define i32 @frameWithCapabilityRegisters(i32 %argc, ptr %argv) {
; CHECK-LABEL: frameWithCapabilityRegisters:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset w19, -8
; CHECK-NEXT:    .cfi_offset w20, -16
; CHECK-NEXT:    .cfi_offset w30, -32
; CHECK-NEXT:    add x0, sp, #12
; CHECK-NEXT:    mov x19, x1
; CHECK-NEXT:    bl foo
; CHECK-NEXT:    ldur w20, [c0, #0]
; CHECK-NEXT:    ldr x0, [x19]
; CHECK-NEXT:    mov w1, w20
; CHECK-NEXT:    bl bar
; CHECK-NEXT:    add w0, w0, w20
; CHECK-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldr x30, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:

  %c = alloca i32, align 4
  call void @llvm.lifetime.start(i64 4, ptr %c)
  %call = call ptr addrspace(200) @foo(ptr nonnull %c)
  %0 = load i32, ptr addrspace(200) %call, align 4
  %1 = load ptr, ptr %argv, align 8
  %call1 = call i32 @bar(ptr %1, i32 %0)
  %add = add nsw i32 %call1, %0
  call void @llvm.lifetime.end(i64 4, ptr %c)
  ret i32 %add
}

declare void @llvm.lifetime.start(i64, ptr nocapture)
declare ptr addrspace(200) @foo(ptr)
declare i32 @bar(ptr, i32)
declare void @llvm.lifetime.end(i64, ptr nocapture)
