; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none-unknown-elf"

; RUN: llc < %s -mtriple=aarch64-none-elf -mattr=+c64,+morello -target-abi=purecap | FileCheck %s

@.str = private unnamed_addr addrspace(200) constant [6 x i8] c"hello\00", align 1
@.str.1 = private unnamed_addr addrspace(200) constant [12 x i8] c"some string\00", align 1
@ext = external unnamed_addr addrspace(200) constant [12 x i8]

; Use a constant string.
define i8 addrspace(200)* @foo() local_unnamed_addr addrspace(200) {
; CHECK-LABEL: foo:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    adrp c0, .L.str
; CHECK-NEXT:    add c0, c0, :lo12:.L.str
; CHECK-NEXT:    clrperm c0, c0, wx
; CHECK-NEXT:    scbnds c0, c0, #6 // =6
; CHECK-NEXT:    ret c30
entry:
  ret i8 addrspace(200)* getelementptr inbounds ([6 x i8], [6 x i8] addrspace(200)* @.str, i64 0, i64 0)
}

; Use a constant string with an addend.
define i8 addrspace(200)* @bar() local_unnamed_addr addrspace(200) {
; CHECK-LABEL: bar:
; CHECK:       .Lfunc_begin1:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    adrp c0, .L.str.1
; CHECK-NEXT:    add c0, c0, :lo12:.L.str.1
; CHECK-NEXT:    clrperm c0, c0, wx
; CHECK-NEXT:    scbnds c0, c0, #12 // =12
; CHECK-NEXT:    add c0, c0, #1 // =1
; CHECK-NEXT:    ret c30
entry:
  ret i8 addrspace(200)* getelementptr inbounds ([12 x i8], [12 x i8] addrspace(200)* @.str.1, i64 0, i64 1)
}

define i8 addrspace(200)* @baz() local_unnamed_addr addrspace(200) {
; CHECK-LABEL: baz:
; CHECK:       .Lfunc_begin2:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    adrp c0, :got:ext
; CHECK-NEXT:    ldr c0, [c0, :got_lo12:ext]
; CHECK-NEXT:    add c0, c0, #1 // =1
; CHECK-NEXT:    ret c30
entry:
  ret i8 addrspace(200)* getelementptr inbounds ([12 x i8], [12 x i8] addrspace(200)* @ext, i64 0, i64 1)
}
