; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -target-abi purecap -mattr=+morello,+c64 -o - -interleaved-load-combine %s -S | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none-unknown-elf"

%struct.blam = type { %struct.wibble }
%struct.wibble = type { ptr addrspace(200), i64, i32, ptr addrspace(200) }
%struct.wobble = type { float, float }

define void @pluto(ptr addrspace(200) nonnull dereferenceable(48) %arg, ptr addrspace(200) %arg1, i64 %arg2, i64 %arg3, i64 %arg4) unnamed_addr addrspace(200)  align 2 {
; CHECK-LABEL: define void @pluto
; CHECK-SAME: (ptr addrspace(200) nonnull dereferenceable(48) [[ARG:%.*]], ptr addrspace(200) [[ARG1:%.*]], i64 [[ARG2:%.*]], i64 [[ARG3:%.*]], i64 [[ARG4:%.*]]) unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] align 2 {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br i1 false, label [[BB15:%.*]], label [[BB5:%.*]]
; CHECK:       bb5:
; CHECK-NEXT:    [[TMP:%.*]] = lshr i64 undef, 1
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <4 x float>, ptr addrspace(200) undef, i64 [[TMP]]
; CHECK-NEXT:    [[INTERLEAVED_WIDE_LOAD:%.*]] = load <8 x float>, ptr addrspace(200) [[TMP6]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = load <4 x float>, ptr addrspace(200) [[TMP6]], align 16
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 undef, 2
; CHECK-NEXT:    [[TMP9:%.*]] = lshr i64 [[TMP8]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds <4 x float>, ptr addrspace(200) undef, i64 [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = load <4 x float>, ptr addrspace(200) [[TMP10]], align 16
; CHECK-NEXT:    [[INTERLEAVED_SHUFFLE:%.*]] = shufflevector <8 x float> [[INTERLEAVED_WIDE_LOAD]], <8 x float> poison, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP7]], <4 x float> [[TMP11]], <4 x i32> <i32 0, i32 2, i32 4, i32 6>
; CHECK-NEXT:    [[INTERLEAVED_SHUFFLE1:%.*]] = shufflevector <8 x float> [[INTERLEAVED_WIDE_LOAD]], <8 x float> poison, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x float> [[TMP7]], <4 x float> [[TMP11]], <4 x i32> <i32 1, i32 3, i32 5, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = tail call <4 x float> @llvm.fma.v4f32(<4 x float> undef, <4 x float> undef, <4 x float> undef)
; CHECK-NEXT:    unreachable
; CHECK:       bb15:
; CHECK-NEXT:    ret void
;
bb:
  br i1 false, label %bb15, label %bb5

bb5:
  %tmp = lshr i64 undef, 1
  %tmp6 = getelementptr inbounds <4 x float>, ptr addrspace(200) undef, i64 %tmp
  %tmp7 = load <4 x float>, ptr addrspace(200) %tmp6, align 16
  %tmp8 = add i64 undef, 2
  %tmp9 = lshr i64 %tmp8, 1
  %tmp10 = getelementptr inbounds <4 x float>, ptr addrspace(200) undef, i64 %tmp9
  %tmp11 = load <4 x float>, ptr addrspace(200) %tmp10, align 16
  %tmp12 = shufflevector <4 x float> %tmp7, <4 x float> %tmp11, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %tmp13 = shufflevector <4 x float> %tmp7, <4 x float> %tmp11, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %tmp14 = tail call <4 x float> @llvm.fma.v4f32(<4 x float> undef, <4 x float> undef, <4 x float> undef)
  unreachable

bb15:
  ret void
}

declare <4 x float> @llvm.fma.v4f32(<4 x float>, <4 x float>, <4 x float>) addrspace(200)
