// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %cheri_purecap_cc1 -emit-llvm -o - %s \
// RUN:   -disable-O0-optnone | opt -S -passes=mem2reg,instcombine \
// RUN:   | FileCheck %s --check-prefix=MIPS
// RUN: %riscv32_cheri_purecap_cc1 -emit-llvm -o - %s \
// RUN:   -disable-O0-optnone | opt -S -passes=mem2reg,instcombine \
// RUN:   | FileCheck %s --check-prefix=RV32I
// RUN: %riscv32_cheri_purecap_cc1 -target-feature +a -emit-llvm -o - %s \
// RUN:   -disable-O0-optnone | opt -S -passes=mem2reg,instcombine \
// RUN:   | FileCheck %s --check-prefix=RV32A
// RUN: %riscv64_cheri_purecap_cc1 -emit-llvm -o - %s \
// RUN:   -disable-O0-optnone | opt -S -passes=mem2reg,instcombine \
// RUN:   | FileCheck %s --check-prefix=RV64I
// RUN: %riscv64_cheri_purecap_cc1 -target-feature +a -emit-llvm -o - %s \
// RUN:   -disable-O0-optnone | opt -S -passes=mem2reg,instcombine \
// RUN:   | FileCheck %s --check-prefix=RV64A
// RUN: %clang_cc1 -triple aarch64 -target-feature +morello \
// RUN:   -target-feature +c64 -target-abi purecap -emit-llvm -o - %s \
// RUN:   -disable-O0-optnone | opt -S -passes=mem2reg,instcombine \
// RUN:   | FileCheck %s --check-prefix=MORELLO

/// Verify that S1 is treated the same as a capability (i.e. uses an optimised
/// libcall or real atomic).

struct S1 {
  void *p;
};

struct S2 {
  void *p, *q;
};

// MIPS-LABEL: define dso_local void @S1_load
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[TMP0:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[PTR]] monotonic, align 16
// MIPS-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[RET]], align 16
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S1_load
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[CALL:%.*]] = call ptr addrspace(200) @__atomic_load_cap(ptr addrspace(200) noundef [[PTR]], i32 noundef 0)
// RV32I-NEXT:    store ptr addrspace(200) [[CALL]], ptr addrspace(200) [[RET]], align 8
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S1_load
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[TMP0:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[PTR]] monotonic, align 8
// RV32A-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[RET]], align 8
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S1_load
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[CALL:%.*]] = call ptr addrspace(200) @__atomic_load_cap(ptr addrspace(200) noundef [[PTR]], i32 noundef signext 0)
// RV64I-NEXT:    store ptr addrspace(200) [[CALL]], ptr addrspace(200) [[RET]], align 16
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S1_load
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[TMP0:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[PTR]] monotonic, align 16
// RV64A-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[RET]], align 16
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S1_load
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[TMP0:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[PTR]] monotonic, align 16
// MORELLO-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[RET]], align 16
// MORELLO-NEXT:    ret void
//
void S1_load(_Atomic struct S1 *ptr, struct S1 *ret) {
  *ret = __c11_atomic_load(ptr, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S1_store
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// MIPS-NEXT:    store atomic ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[PTR]] monotonic, align 16
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S1_store
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 8
// RV32I-NEXT:    call void @__atomic_store_cap(ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[TMP0]], i32 noundef 0)
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S1_store
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 8
// RV32A-NEXT:    store atomic ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[PTR]] monotonic, align 8
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S1_store
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// RV64I-NEXT:    call void @__atomic_store_cap(ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[TMP0]], i32 noundef signext 0)
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S1_store
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// RV64A-NEXT:    store atomic ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[PTR]] monotonic, align 16
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S1_store
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// MORELLO-NEXT:    store atomic ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[PTR]] monotonic, align 16
// MORELLO-NEXT:    ret void
//
void S1_store(_Atomic struct S1 *ptr, struct S1 *val) {
  __c11_atomic_store(ptr, *val, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S1_exchange
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// MIPS-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP0]] monotonic, align 16
// MIPS-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RET]], align 16
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S1_exchange
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 8
// RV32I-NEXT:    [[CALL:%.*]] = call ptr addrspace(200) @__atomic_exchange_cap(ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[TMP0]], i32 noundef 0)
// RV32I-NEXT:    store ptr addrspace(200) [[CALL]], ptr addrspace(200) [[RET]], align 8
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S1_exchange
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 8
// RV32A-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP0]] monotonic, align 8
// RV32A-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RET]], align 8
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S1_exchange
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// RV64I-NEXT:    [[CALL:%.*]] = call ptr addrspace(200) @__atomic_exchange_cap(ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[TMP0]], i32 noundef signext 0)
// RV64I-NEXT:    store ptr addrspace(200) [[CALL]], ptr addrspace(200) [[RET]], align 16
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S1_exchange
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// RV64A-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP0]] monotonic, align 16
// RV64A-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RET]], align 16
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S1_exchange
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[VAL]], align 16
// MORELLO-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP0]] monotonic, align 16
// MORELLO-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[RET]], align 16
// MORELLO-NEXT:    ret void
//
void S1_exchange(_Atomic struct S1 *ptr, struct S1 *val, struct S1 *ret) {
  *ret = __c11_atomic_exchange(ptr, *val, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S1_compare_exchange
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DESIRED]], align 16
// MIPS-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[EXPECTED]], align 16
// MIPS-NEXT:    [[TMP2:%.*]] = cmpxchg weak ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[TMP0]] monotonic monotonic, align 16
// MIPS-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 1
// MIPS-NEXT:    br i1 [[TMP3]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// MIPS:       cmpxchg.store_expected:
// MIPS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 0
// MIPS-NEXT:    store ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[EXPECTED]], align 16
// MIPS-NEXT:    br label [[CMPXCHG_CONTINUE]]
// MIPS:       cmpxchg.continue:
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S1_compare_exchange
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DESIRED]], align 8
// RV32I-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange_cap(ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef [[TMP0]], i32 noundef 0, i32 noundef 0)
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S1_compare_exchange
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DESIRED]], align 8
// RV32A-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[EXPECTED]], align 8
// RV32A-NEXT:    [[TMP2:%.*]] = cmpxchg weak ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[TMP0]] monotonic monotonic, align 8
// RV32A-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 1
// RV32A-NEXT:    br i1 [[TMP3]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// RV32A:       cmpxchg.store_expected:
// RV32A-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 0
// RV32A-NEXT:    store ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[EXPECTED]], align 8
// RV32A-NEXT:    br label [[CMPXCHG_CONTINUE]]
// RV32A:       cmpxchg.continue:
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S1_compare_exchange
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DESIRED]], align 16
// RV64I-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange_cap(ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef [[TMP0]], i32 noundef signext 0, i32 noundef signext 0)
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S1_compare_exchange
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DESIRED]], align 16
// RV64A-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[EXPECTED]], align 16
// RV64A-NEXT:    [[TMP2:%.*]] = cmpxchg weak ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[TMP0]] monotonic monotonic, align 16
// RV64A-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 1
// RV64A-NEXT:    br i1 [[TMP3]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// RV64A:       cmpxchg.store_expected:
// RV64A-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 0
// RV64A-NEXT:    store ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[EXPECTED]], align 16
// RV64A-NEXT:    br label [[CMPXCHG_CONTINUE]]
// RV64A:       cmpxchg.continue:
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S1_compare_exchange
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DESIRED]], align 16
// MORELLO-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[EXPECTED]], align 16
// MORELLO-NEXT:    [[TMP2:%.*]] = cmpxchg weak ptr addrspace(200) [[PTR]], ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[TMP0]] monotonic monotonic, align 16
// MORELLO-NEXT:    [[TMP3:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 1
// MORELLO-NEXT:    br i1 [[TMP3]], label [[CMPXCHG_CONTINUE:%.*]], label [[CMPXCHG_STORE_EXPECTED:%.*]]
// MORELLO:       cmpxchg.store_expected:
// MORELLO-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 0
// MORELLO-NEXT:    store ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[EXPECTED]], align 16
// MORELLO-NEXT:    br label [[CMPXCHG_CONTINUE]]
// MORELLO:       cmpxchg.continue:
// MORELLO-NEXT:    ret void
//
void S1_compare_exchange(_Atomic struct S1 *ptr, struct S1 *expected, struct S1 *desired) {
  __c11_atomic_compare_exchange_weak(ptr, expected, *desired, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S2_load
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MIPS-NEXT:    call void @__atomic_load(i64 noundef zeroext 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef signext 0)
// MIPS-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S2_load
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV32I-NEXT:    call void @__atomic_load(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef 0)
// RV32I-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(16) [[ATOMIC_TEMP]], i32 16, i1 false)
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S2_load
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV32A-NEXT:    call void @__atomic_load(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef 0)
// RV32A-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(16) [[ATOMIC_TEMP]], i32 16, i1 false)
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S2_load
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64I-NEXT:    call void @__atomic_load(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef signext 0)
// RV64I-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S2_load
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64A-NEXT:    call void @__atomic_load(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef signext 0)
// RV64A-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S2_load
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MORELLO-NEXT:    call void @__atomic_load(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef 0)
// MORELLO-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// MORELLO-NEXT:    ret void
//
void S2_load(_Atomic struct S2 *ptr, struct S2 *ret) {
  *ret = __c11_atomic_load(ptr, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S2_store
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MIPS-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// MIPS-NEXT:    call void @__atomic_store(i64 noundef zeroext 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef signext 0)
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S2_store
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// RV32I-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[VAL]], i32 16, i1 false)
// RV32I-NEXT:    call void @__atomic_store(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef 0)
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S2_store
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// RV32A-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[VAL]], i32 16, i1 false)
// RV32A-NEXT:    call void @__atomic_store(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef 0)
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S2_store
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64I-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// RV64I-NEXT:    call void @__atomic_store(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef signext 0)
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S2_store
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64A-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// RV64A-NEXT:    call void @__atomic_store(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef signext 0)
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S2_store
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MORELLO-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// MORELLO-NEXT:    call void @__atomic_store(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef 0)
// MORELLO-NEXT:    ret void
//
void S2_store(_Atomic struct S2 *ptr, struct S2 *val) {
  __c11_atomic_store(ptr, *val, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S2_exchange
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MIPS-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2]], align 16, addrspace(200)
// MIPS-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// MIPS-NEXT:    call void @__atomic_exchange(i64 noundef zeroext 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef signext 0)
// MIPS-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S2_exchange
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// RV32I-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2]], align 16, addrspace(200)
// RV32I-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[VAL]], i32 16, i1 false)
// RV32I-NEXT:    call void @__atomic_exchange(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef 0)
// RV32I-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(16) [[ATOMIC_TEMP]], i32 16, i1 false)
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S2_exchange
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// RV32A-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2]], align 16, addrspace(200)
// RV32A-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[VAL]], i32 16, i1 false)
// RV32A-NEXT:    call void @__atomic_exchange(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef 0)
// RV32A-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(16) [[ATOMIC_TEMP]], i32 16, i1 false)
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S2_exchange
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64I-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2]], align 16, addrspace(200)
// RV64I-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// RV64I-NEXT:    call void @__atomic_exchange(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef signext 0)
// RV64I-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S2_exchange
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64A-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2]], align 16, addrspace(200)
// RV64A-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// RV64A-NEXT:    call void @__atomic_exchange(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef signext 0)
// RV64A-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S2_exchange
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[VAL:%.*]], ptr addrspace(200) noundef [[RET:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MORELLO-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca [[STRUCT_S2]], align 16, addrspace(200)
// MORELLO-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[VAL]], i64 32, i1 false)
// MORELLO-NEXT:    call void @__atomic_exchange(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull [[ATOMIC_TEMP]], i32 noundef 0)
// MORELLO-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[RET]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[ATOMIC_TEMP]], i64 32, i1 false)
// MORELLO-NEXT:    ret void
//
void S2_exchange(_Atomic struct S2 *ptr, struct S2 *val, struct S2 *ret) {
  *ret = __c11_atomic_exchange(ptr, *val, __ATOMIC_RELAXED);
}

// MIPS-LABEL: define dso_local void @S2_compare_exchange
// MIPS-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// MIPS-NEXT:  entry:
// MIPS-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MIPS-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DESIRED]], i64 32, i1 false)
// MIPS-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i64 noundef zeroext 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef signext 0, i32 noundef signext 0)
// MIPS-NEXT:    ret void
//
// RV32I-LABEL: define dso_local void @S2_compare_exchange
// RV32I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32I-NEXT:  entry:
// RV32I-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// RV32I-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DESIRED]], i32 16, i1 false)
// RV32I-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef 0, i32 noundef 0)
// RV32I-NEXT:    ret void
//
// RV32A-LABEL: define dso_local void @S2_compare_exchange
// RV32A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV32A-NEXT:  entry:
// RV32A-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 8, addrspace(200)
// RV32A-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 8 dereferenceable(16) [[DESIRED]], i32 16, i1 false)
// RV32A-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i32 noundef 16, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef 0, i32 noundef 0)
// RV32A-NEXT:    ret void
//
// RV64I-LABEL: define dso_local void @S2_compare_exchange
// RV64I-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64I-NEXT:  entry:
// RV64I-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64I-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DESIRED]], i64 32, i1 false)
// RV64I-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef signext 0, i32 noundef signext 0)
// RV64I-NEXT:    ret void
//
// RV64A-LABEL: define dso_local void @S2_compare_exchange
// RV64A-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// RV64A-NEXT:  entry:
// RV64A-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// RV64A-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DESIRED]], i64 32, i1 false)
// RV64A-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef signext 0, i32 noundef signext 0)
// RV64A-NEXT:    ret void
//
// MORELLO-LABEL: define dso_local void @S2_compare_exchange
// MORELLO-SAME: (ptr addrspace(200) noundef [[PTR:%.*]], ptr addrspace(200) noundef [[EXPECTED:%.*]], ptr addrspace(200) noundef [[DESIRED:%.*]]) addrspace(200) #[[ATTR0]] {
// MORELLO-NEXT:  entry:
// MORELLO-NEXT:    [[DOTATOMICTMP:%.*]] = alloca [[STRUCT_S2:%.*]], align 16, addrspace(200)
// MORELLO-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DOTATOMICTMP]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[DESIRED]], i64 32, i1 false)
// MORELLO-NEXT:    [[CALL:%.*]] = call i1 @__atomic_compare_exchange(i64 noundef 32, ptr addrspace(200) noundef [[PTR]], ptr addrspace(200) noundef [[EXPECTED]], ptr addrspace(200) noundef nonnull [[DOTATOMICTMP]], i32 noundef 0, i32 noundef 0)
// MORELLO-NEXT:    ret void
//
void S2_compare_exchange(_Atomic struct S2 *ptr, struct S2 *expected, struct S2 *desired) {
  __c11_atomic_compare_exchange_weak(ptr, expected, *desired, __ATOMIC_RELAXED, __ATOMIC_RELAXED);
}
