// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple aarch64-none-elf -target-feature +morello -target-feature +c64 -target-abi purecap %s -emit-llvm -o -  | FileCheck %s

// CHECK-LABEL: @f1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A1_ADDR:%.*]] = alloca i8 addrspace(200)*, align 16, addrspace(200)
// CHECK-NEXT:    [[A2_ADDR:%.*]] = alloca i64, align 8, addrspace(200)
// CHECK-NEXT:    store i8 addrspace(200)* [[A1:%.*]], i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    store i64 [[A2:%.*]], i64 addrspace(200)* [[A2_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, i64 addrspace(200)* [[A2_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* null, i64 [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP0]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP2]])
// CHECK-NEXT:    [[ADD:%.*]] = add i64 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TMP5:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* [[TMP0]], i64 [[ADD]])
// CHECK-NEXT:    ret i8 addrspace(200)* [[TMP5]]
//
__uintcap_t f1(__uintcap_t a1, unsigned long long a2) {
  return a1 + a2;
}
// CHECK-LABEL: @f2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A1_ADDR:%.*]] = alloca i8 addrspace(200)*, align 16, addrspace(200)
// CHECK-NEXT:    [[A2_ADDR:%.*]] = alloca i64, align 8, addrspace(200)
// CHECK-NEXT:    store i8 addrspace(200)* [[A1:%.*]], i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    store i64 [[A2:%.*]], i64 addrspace(200)* [[A2_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, i64 addrspace(200)* [[A2_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* null, i64 [[TMP0]])
// CHECK-NEXT:    [[TMP2:%.*]] = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP1]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP2]])
// CHECK-NEXT:    [[ADD:%.*]] = add i64 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TMP5:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* [[TMP2]], i64 [[ADD]])
// CHECK-NEXT:    ret i8 addrspace(200)* [[TMP5]]
//
__uintcap_t f2(__uintcap_t a1, unsigned long long a2) {
  return a2 + a1;
}

// The following loses the top bits of the __uint128_t in an attempt to
// preserve the capability metadata. It should really give a warning.

// CHECK-LABEL: @f3(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A1_ADDR:%.*]] = alloca i8 addrspace(200)*, align 16, addrspace(200)
// CHECK-NEXT:    [[A2_ADDR:%.*]] = alloca i128, align 16, addrspace(200)
// CHECK-NEXT:    store i8 addrspace(200)* [[A1:%.*]], i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    store i128 [[A2:%.*]], i128 addrspace(200)* [[A2_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load i128, i128 addrspace(200)* [[A2_ADDR]], align 16
// CHECK-NEXT:    [[CONV:%.*]] = trunc i128 [[TMP1]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* null, i64 [[CONV]])
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP0]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP2]])
// CHECK-NEXT:    [[ADD:%.*]] = add i64 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TMP5:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* [[TMP0]], i64 [[ADD]])
// CHECK-NEXT:    ret i8 addrspace(200)* [[TMP5]]
//
__uintcap_t f3(__uintcap_t a1, __uint128_t a2) {
  return a1 + a2;
}

// CHECK-LABEL: @f4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A1_ADDR:%.*]] = alloca i8 addrspace(200)*, align 16, addrspace(200)
// CHECK-NEXT:    [[A2_ADDR:%.*]] = alloca i128, align 16, addrspace(200)
// CHECK-NEXT:    store i8 addrspace(200)* [[A1:%.*]], i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    store i128 [[A2:%.*]], i128 addrspace(200)* [[A2_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i128, i128 addrspace(200)* [[A2_ADDR]], align 16
// CHECK-NEXT:    [[CONV:%.*]] = trunc i128 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* null, i64 [[CONV]])
// CHECK-NEXT:    [[TMP2:%.*]] = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* [[A1_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP1]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(i8 addrspace(200)* [[TMP2]])
// CHECK-NEXT:    [[ADD:%.*]] = add i64 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TMP5:%.*]] = call i8 addrspace(200)* @llvm.cheri.cap.address.set.i64(i8 addrspace(200)* [[TMP2]], i64 [[ADD]])
// CHECK-NEXT:    ret i8 addrspace(200)* [[TMP5]]
//
__uintcap_t f4(__uintcap_t a1, __uint128_t a2) {
  return a2 + a1;
}
