; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -march=aarch64 -target-abi purecap -mattr=+morello,+c64 %s -S -passes=indvars -o - | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none-unknown-elf"

; inc1.lcssa takes the value of the backedge taken count so gets simplified.
; In order to expand the backedge taken count we need to expand a ptrtoint
; expression for a cheri capability which needs to use a call to
; llvm.cheri.cap.address.get.i64.

define i32 @foo(ptr addrspace(200) %a) addrspace(200) {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
; CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4, addrspace(200)
; CHECK-NEXT:    [[I:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
; CHECK-NEXT:    store ptr addrspace(200) [[A:%.*]], ptr addrspace(200) [[A_ADDR]], align 16
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[A_ADDR]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[TMP0]])
; CHECK-NEXT:    [[SUM_PROMOTED:%.*]] = load i32, ptr addrspace(200) [[SUM]], align 4
; CHECK-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP1]], i64 44)
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[UMAX]], -41
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i64 [[TMP2]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = shl nuw i64 [[TMP3]], 2
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], 44
; CHECK-NEXT:    br label [[FOR_COND:%.*]]
; CHECK:       for.cond:
; CHECK-NEXT:    br i1 false, label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    br label [[FOR_INC:%.*]]
; CHECK:       for.inc:
; CHECK-NEXT:    br label [[FOR_COND]]
; CHECK:       for.end:
; CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[SUM_PROMOTED]], [[TMP4]]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[TMP6]]
; CHECK-NEXT:    store ptr addrspace(200) [[SCEVGEP]], ptr addrspace(200) [[I]], align 16
; CHECK-NEXT:    store i32 [[TMP7]], ptr addrspace(200) [[SUM]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(200) [[SUM]], align 4
; CHECK-NEXT:    ret i32 [[TMP8]]
;
entry:
  %a.addr = alloca ptr addrspace(200), align 16, addrspace(200)
  %sum = alloca i32, align 4, addrspace(200)
  %i = alloca ptr addrspace(200), align 16, addrspace(200)
  store ptr addrspace(200) %a, ptr addrspace(200) %a.addr, align 16
  %0 = load ptr addrspace(200), ptr addrspace(200) %a.addr, align 16
  %sum.promoted = load i32, ptr addrspace(200) %sum, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %inc1 = phi i32 [ %sum.promoted, %entry ], [ %inc, %for.inc ]
  %storemerge = phi ptr addrspace(200) [ getelementptr (i8, ptr addrspace(200) null, i64 44), %entry ], [ %incdec.ptr, %for.inc ]
  %cmp = icmp ult ptr addrspace(200) %storemerge, %0
  br i1 %cmp, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %inc = add nsw i32 %inc1, 1
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %incdec.ptr = getelementptr inbounds i32, ptr addrspace(200) %storemerge, i64 1
  br label %for.cond

for.end:                                          ; preds = %for.cond
  %inc1.lcssa = phi i32 [ %inc1, %for.cond ]
  %storemerge.lcssa = phi ptr addrspace(200) [ %storemerge, %for.cond ]
  store ptr addrspace(200) %storemerge.lcssa, ptr addrspace(200) %i, align 16
  store i32 %inc1.lcssa, ptr addrspace(200) %sum, align 4
  %1 = load i32, ptr addrspace(200) %sum, align 4
  ret i32 %1
}
