// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -Wall -Werror -triple aarch64-none-elf -target-feature +c64 -target-abi purecap -disable-O0-optnone -emit-llvm -o - %s | opt -S -passes=mem2reg | FileCheck %s

// CHECK-LABEL: define dso_local i32 @test_eh_return_data_regno
// CHECK-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RES:%.*]] = alloca i32, align 4, addrspace(200)
// CHECK-NEXT:    store volatile i32 198, ptr addrspace(200) [[RES]], align 4
// CHECK-NEXT:    store volatile i32 1, ptr addrspace(200) [[RES]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load volatile i32, ptr addrspace(200) [[RES]], align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int test_eh_return_data_regno()
{
  volatile int res;
  res = __builtin_eh_return_data_regno(0);
  res = __builtin_eh_return_data_regno(1);
  return res;
}
