// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple aarch64-none-elf -target-feature +c64 -target-abi purecap -emit-llvm -o - -mllvm -cheri-cap-table-abi=pcrel %s | FileCheck %s

void bar();
void baz();

// CHECK-LABEL: @foo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4, addrspace(200)
// CHECK-NEXT:    [[LABEL:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store i32 [[A:%.*]], ptr addrspace(200) [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(200) [[A_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = zext i1 [[TOBOOL]] to i64
// CHECK-NEXT:    [[COND:%.*]] = select i1 [[TOBOOL]], ptr addrspace(200) blockaddress(@foo, [[L:%.*]]), ptr addrspace(200) blockaddress(@foo, [[M:%.*]])
// CHECK-NEXT:    store ptr addrspace(200) [[COND]], ptr addrspace(200) [[LABEL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[LABEL]], align 16
// CHECK-NEXT:    br label [[INDIRECTGOTO:%.*]]
// CHECK:       l:
// CHECK-NEXT:    call void @bar()
// CHECK-NEXT:    br label [[RETURN:%.*]]
// CHECK:       m:
// CHECK-NEXT:    call void @baz()
// CHECK-NEXT:    br label [[RETURN]]
// CHECK:       return:
// CHECK-NEXT:    ret void
// CHECK:       indirectgoto:
// CHECK-NEXT:    [[INDIRECT_GOTO_DEST:%.*]] = phi ptr addrspace(200) [ [[TMP2]], [[ENTRY:%.*]] ]
// CHECK-NEXT:    indirectbr ptr addrspace(200) [[INDIRECT_GOTO_DEST]], [label [[L]], label %m]
//
void foo (int a)
{

  void *label = a ? &&l : &&m;
  goto *label;
l:
  bar();
  return;
m:
  baz();
}
